### ISSUE TITLE
request mappings view doesn't respect @GetMapping, @PostMapping etc.

### ISSUE THREAD

**Issue by dominik42** [spring-projects/spring-ide#101]
If @RestController annotated classes uses the newer @GetMapping, @PostMapping, @PutMapping or @DeleteMapping request mapping annotations, those mappings are not shown in the request mapping view, neither via 
* `<Spring Boot Project>` / Spring Tools / Show RequestMappings
* Spring Explorer View / `<Spring Boot Project>` / Beans / Request Mapping
* Boot Dashboard / `<Spring Boot Project>` / Show Properties / Request Mappings

The Spring Explorer at least shows the request mapping created by the class level annotation `@RequestMapping` but none of the method level annotations.

If the methods are annotated with @RequestMapping instaed, all mappings are properly shown.
I would expect, that the request mappings also be visible, if the newer annotations are used.

This behaviour was described first in https://stackoverflow.com/questions/42900133/spring-tool-suite-ignores-getmapping-postmapping

Kind regards
Dominik

**Comment by martinlippert** [comment]
Hey Dominik, thanks for filing this issue, much appreciated. Makes absolutely sense to add this to the tooling. I am wondering why the boot dashboard doesn't show those request mappings (since they are retrieved from the running app and not inferred from the source code), but we will have to investigate this.

Will put that into our tracker for the 3.9.0 release, since we will not be able to squeeze that into the 3.8.4 release anymore. Sorry for that.

**Comment by martinlippert** [comment]
I think he mentioned three different places in his comment above, differentiating the spring explorer from the boot dash props view. Anyhow, need to investigate. @dominik42 if you have a sample project that illustrates the problem, feel free to attach. Always helps!!!

**Comment by dominik42** [comment]
After upgrade to 3.8.4.RELEASE the situation is slightly different:
* `<Spring Boot Project>` / Spring Tools / Show RequestMappings
The request mappings annotated with the new annotation are not show, the other are shown
* Spring Explorer View / `<Spring Boot Project>` / Beans / Request Mapping
All request mappings are shown (for new and already established annotations)
* Boot Dashboard / <Spring Boot Project> / Show Properties / Request Mappings
No request mappings (besides the mappings for all those actuator endpoints) are shown
Attached you can find a Spring Boot Demo project created right from the Spring Boot Initializr. I've added different @RestController annotated classes in order to showcase the different annotations and their results within the RequestMapping views.

[demo.zip](https://github.com/spring-projects/spring-ide/files/913331/demo.zip)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

Thanks a lot for the demo project, that made testing these various settings a lot easier.

I implemented this now and it works in the request mappings view as well as the spring explorer.

The request mappings tab in the properties view of the boot dashboard is already showing all those request mappings of the running app.

Looks to me like this is complete now. Will be shipped as part of the upcoming STS 3.9.0 release.
