### ISSUE TITLE
Support for deprecation level

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-ide#142]
Spring Boot has introduced a new property in the `deprecation` object called `level`. 

What is expected from the IDE is [documented here](https://github.com/spring-projects/spring-boot/wiki/IDE-binding-features#deprecation)

The  `spring-boot-configuration-metadata` module on `master` has been updated to parse this new property. 

We intend to insert a bunch of such `error` properties for the things that we are breaking in Spring Boot 2 so it would be good if STS could show them as an error.

While the code has been added to Spring Boot 2, the annotation processor doesn't do anything with this as "error" properties are always defined in manual meta-data so please do not constraint its use to Spring Boot 2 only.

**Comment by snicoll** [comment]
Curious, what does `delivered ` means?

**Comment by martinlippert** [comment]
We sync this with our pivotal tracker instance, so "delivered" means that the associated story got implemented and is ready for acceptance in tracker. Code is committed to the repo and a snapshot build of this is available from the project-specific p2 update site... :-)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

do you have a pointer to an existing property that is defined as level=error?

**Comment by snicoll** [comment]
Not yet but I intend to add some on `master` soon. There are [examples used in tests](https://github.com/spring-projects/spring-boot/blob/cdf5f6e0eecc8cdc97454a3e50a7c99b6b8f4b7f/spring-boot-tools/spring-boot-configuration-metadata/src/test/resources/metadata/configuration-metadata-deprecated.json)
