### ISSUE TITLE
Where are the MD5 hashes to verify the download

### ISSUE THREAD

**Issue by davidnewcomb** [spring-projects/spring-ide#144]
I'm downloading the latest version of STS ( http://download.springsource.com/release/STS/3.8.4.RELEASE/dist/e4.6/spring-tool-suite-3.8.4.RELEASE-e4.6.3-win32-x86_64.zip ) but when I unpack it I get a corrupted maven jar which is preventing me from importing maven projects.

Normally the download page contains MD5 hashes so that I can verify that what I now have on my computer is the same as what is on your download servers. Unfortunately the network where I'm currently working isn't run by the best people :( So I have no way to verify if it's you or me.

Please can you add download verification hashs or at least provide an MD5 hash for the above download.

**Comment by martinlippert** [comment]
You can find the MD5 for that file here: http://download.springsource.com/release/STS/3.8.4.RELEASE/dist/e4.6/spring-tool-suite-3.8.4.RELEASE-e4.6.3-win32-x86_64.zip.md5

Which file is corrupted in your case? A maven jar file?
In case something in your local Maven repository is corrupted (which seem to happen quite frequently), I would recommend to delete the local maven repository and import the project again. Just in case...

**Comment by davidnewcomb** [comment]
The error comes when I uncompress your zip file, which is why I wanted the MD5 sum. Thank you for providing it. Mine is different to yours so I'll have to get on to our network people. Our network seems to die after downloading 190MB and I don't think the resume download is working with the corporate proxy server so I get a corruption 190MB along the zip file around the extraction of m2e/plexus-utils.

Are the md5 files always available for your releases or did you just generate them for me this time. There doesn't appear to be a link on the download page to reach them. You can change the tags for this issue to documentation and include the md5 tags in the web page. I'm sure they used to me there which is why I was a bit surprised that I couldn't find them.

**Comment by martinlippert** [comment]
The md5 and sha1 files are always available for every release, but we don't add links to those files on the download page to reduce space on the page and make the page less crowded. But you are right, it is hard to find them if you don't know where they are. We should at least provide a hint that md5 and sha1 checksums can be found under the same download URL + ".md5" and ".sha1".

**Comment by davidnewcomb** [comment]
The md5 link should be front and foremost i.e. next to the download link. Hiding it in the documentation would be as good as useless. And getting people to write their own urls seems like a pretty poor solution to me.
Maybe I saw it on a different site but the md5 link was right next to the download link. I really don't think screen space is an issue. It just feels like an omission to me. The picture below shows what you could have won ;)

![image](https://cloud.githubusercontent.com/assets/951359/26113176/b9f143a6-3a51-11e7-8266-27bf4c2b0c86.png)

**Comment by martinlippert** [comment]
Yepp, I filed an issue for the website project to include those links again. Makes sense. Thanks for the feedback.
