### ISSUE TITLE
Error when compiling very simple project with Eclipse 4.6.3 and Spring Project Builder

### ISSUE THREAD

**Issue by CyrilPZ** [spring-projects/spring-ide#145]
Hi !

I'm trying the spring STS + Eclipse 4.6 as a new environment to develop our new Spring boot projects, and have a strange issue with a very simple Spring boot test project:

when I compile the project, I get an error popup with the details:

Errors occurred during the build.
Errors running builder 'Spring Project Builder' on project 'spring-boot-2'.
org.eclipse.jdt.internal.compiler.env.IBinaryMethod.getParameterAnnotations(I)[Lorg/eclipse/jdt/internal/compiler/env/IBinaryAnnotation;

![error](https://cloud.githubusercontent.com/assets/28762009/26165799/8d0d5362-3b31-11e7-9bfb-b8019abd9581.jpg)

When I press "OK", I can still deploy my test project and start it, but this error popup is a bit strange (and quite annoying, since it is displayed after each "Save").

Note: it wasn't easy to install STS on Eclipse, so maybe there is something broken in the install, I'm not sure about it. I did get the issue detailed here: http://stackoverflow.com/questions/23406047/spring-tool-suite-sts-3-5-0-org-codehaus-groovy-eclipse-is-unknown-in-the-so
and manage to fix it with the solution written, but had to "Check for update" after this and it updated quite a lot of things (related to STS)

Thank you if you can help me on this issue.

**Comment by martinlippert** [comment]
The issue that you refer to is related to having the Groovy-Eclipse extension installed. Is that the case in your installation?

The error that you mention does indeed look like an incompatibility between plugins and/or patched JDT versions. Can you check which plugins you have installed (and their versions)? Especially the Groovy-Eclipse plugins and the Spring IDE plugins?

Also a full stack trace would be useful to see exactly where this problem happens. You can (hopefully) find it in the Error Log view.

**Comment by CyrilPZ** [comment]
Hi,

Thanks for your answer.

I installed the Groovy-Eclipse extension since it seemed to be a requirement for an install of the STS extension (there seems to be a (old) ticket related to this: https://jira.spring.io/browse/STS-3792 ). It was related to vers ion 4.3 of Eclipse, but I got the problem with the latest stable version of Eclipse (4.6)

I took the solution there: http://stackoverflow.com/questions/23406047/spring-tool-suite-sts-3-5-0-org-codehaus-groovy-eclipse-is-unknown-in-the-so

In the Error log, there is is stack trace: 

java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.env.IBinaryMethod.getParameterAnnotations(I)[Lorg/eclipse/jdt/internal/compiler/env/IBinaryAnnotation;
	at org.springframework.ide.eclipse.core.java.TypeStructureCache.parameterAnnotationsEquals(TypeStructureCache.java:458)
	at org.springframework.ide.eclipse.core.java.TypeStructureCache.hasStructuralChanges(TypeStructureCache.java:427)
	at org.springframework.ide.eclipse.core.java.TypeStructureCache.hasStructuralChanges(TypeStructureCache.java:194)
(...)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


A colleague of mine told me about an Eclipse version fully packaged with Spring. I have downloaded this version on the Spring Web site  (Version: 3.8.4.RELEASE / Platform: Eclipse Neon.3 (4.6.3)) and everything is working fine with it, so I will uninstall the standard version + STS plugin, but I wanted to share my problem, because it is a potential issue (I installed STS from a fresh eclipse install).

Best

**Comment by CyrilPZ** [comment]
Update: I think I have found why I have this problem.

I installed STS from the Eclipse Marketplace. There, you have 2 versions of STS : one for Eclipse Helios (3.6), the other for Eclipse, but this version is labelled "STS for Eclipse 3.8.4 RELEASE", so I thought the "3.8.4" was related to Eclipse, but in fact it isn't: it is the STS version.

![image](https://cloud.githubusercontent.com/assets/28762009/26203638/4f1cfcf0-3bdc-11e7-996b-81d5a27082be.png)


So I installed the wrong version of STS, leading to all these bugs.

**Comment by martinlippert** [comment]
Ah, that could be the problem, indeed. Version 3.8.4 refers to the STS component and not Eclipse, correct. But I think it is time to retire the old 2.9.2 release item altogether from the marketplace, before it creates more confusion for more people. Sorry for that. Ok to close this item now?

**Comment by CyrilPZ** [comment]
Yes, this ticket should be closed.

It is not a but. I uninstalled previous version of STS and groovy, and installed latest version of STS and everything is running fine.

Thanks !
