### ISSUE TITLE
STS does not work well with Spring Integration .xsd files

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-ide#149]
Hello 

I am working with: 

* ` STS 3.8.4.RELEASE` 
* `Spring Integration 4.3.9.RELEASE`.

The app works fine, of course it in runtime.

I have two unusual behaviors about the IDE 

**First**

See the two images:

![01](https://cloud.githubusercontent.com/assets/2552795/26699393/5767d4d0-46df-11e7-8fac-9ca752495ff3.png)

![02](https://cloud.githubusercontent.com/assets/2552795/26699450/8c3e8244-46df-11e7-99bf-ce5e95d01afc.png)
 
I don't have idea why the IDE marks with an underline red some attributes (It happens for many SI components, always the same attributes). I have confirmed through the Spring Integration Reference documentation that is valid and again like I said my app works fine. 

If you see the image one you can see that some components are marked with the red circle.

If I put the cursor over the red circle does not appear a pop-up note indicating the error. But if I do double click in the red circle just appears the following: 

![03](https://cloud.githubusercontent.com/assets/2552795/26699631/2823de0c-46e0-11e7-87d9-de31b9e13a4a.png)

**Second**

When I do the `Ctrl + space` to load a list of attributes (it for many SI components) , it does not work how is expected, for example, the following `Service Activator` should show the `input-channel` attribute how is expected, but it does not happen. 

![04](https://cloud.githubusercontent.com/assets/2552795/26700175/038020cc-46e2-11e7-9cac-3c8f254ffc3b.png)

I must write the attribute manually

I think the namespaces are ok:

![05](https://cloud.githubusercontent.com/assets/2552795/26700214/31812840-46e2-11e7-9566-fc920c44378a.png)

The `.xsd` files referenced through the `schemaLocation` has no a version

Not sure if it is a bug or some extra special step must be accomplish to solve these two situations.

Thanks

**Comment by garyrussell** [comment]
Did you enable "Spring Nature" on the project?

For historical reasons, some of the original SI schemas on the internet are outdated; we can't change them without possibly breaking (admittedly very old) user applications.

See the `IMPORTANT` note near the top of [this one](http://www.springframework.org/schema/integration/spring-integration.xsd).

If you enable Spring Nature on the project, STS knows how to find the proper schema in the spring jars (there is special mapping in `META-INF/spring.schemas`).

**Comment by manueljordan** [comment]
Hello @garyrussell 

>Did you enable "Spring Nature" on the project?

No, I didn't. Now works fine. Thank you.  

> For historical reasons, some of the original SI schemas on the internet are outdated; we can't change them without possibly breaking (admittedly very old) user applications.

I am confused about that, I thought the `.xsd` files should be referenced through the .jar files from SI by itself through the `META-INF/spring.schemas` configuration 

> See the IMPORTANT note near the top of this one.
Thanks by that link. Here two things:

- Is that note shared in the SI Reference Documentation?
- The link shared within the note is broken.

> If you enable Spring Nature on the project, STS knows how to find the proper schema in the spring jars > (there is special mapping in META-INF/spring.schemas).

Yes. I have confirmed that. 

Thanks a lot!.

**Comment by martinlippert** [comment]
Closing this one here since it doesn't seem to be an issue with Spring IDE tooling. Thanks @garyrussell for your answer here. Maybe you would like to follow up with Manuel on his questions?

**Comment by garyrussell** [comment]
>I am confused about that, I thought the .xsd files should be referenced through the .jar files from SI by itself through the META-INF/spring.schemas configuration

Yes, Spring Integration (any Spring Project) will resolve the XSDs correctly (at runtime), but unless the tooling is spring-aware (such as by enabling the Spring Project Nature in STS), it won't be resolved in the IDE.

Spring-aware IDEs do the resolution via the META-INF data.

I have opened a [JIRA issue](https://jira.spring.io/browse/INT-4295) to address the other items.

**Comment by garyrussell** [comment]
Thanks for pointing me back to this @martinlippert

**Comment by manueljordan** [comment]
Thanks by your explanation @garyrussell. Thanks by all @martinlippert ...

Perhaps add in the Spring Integration Reference documentation a note about the `Spring Project Nature in STS` would be valuable too.

**Comment by mauromol** [comment]
Just to let you know I was hit by this problem too, adding the Spring Project Nature fixed it. It was not that intuitive to find out (thanks to this report!), especially because I thought that nature was already in place  (but it was not indeed) :-)
