### ISSUE TITLE
Spring boot launch configuration: using the classpath tab breaks classpath

### ISSUE THREAD

**Issue by bluebilt** [spring-projects/spring-ide#152]
Making any change on the classpath tab of a launch configuration of type 'Spring Boot App' will add unwanted jars to the classpath. The attached demo application demonstrates this.

(https://github.com/spring-projects/spring-ide/files/1071503/boot-launcher-bug.zip)

1. **boot-launcher working**: contains the standard classpath
2. **boot-launcher broken**: adding a folder to the classpath through the GUI does not work and other dependencies suddenly appear on the classpath (in this case the maven test dependencies)
3. **java-launcher working**: adding a folder to the classpath through the GUI works fine on java launchers
4. **boot-launcher fixed**: manually copying the relevant xml snippet from the java-launcher to the boot-launcher fixes the problem

**Comment by bluebilt** [comment]
Bug still present in STS 3.9.0. After adding an external folder STS still replaces the maven classpath by the default classpath.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

The reason for the problem was that when using the 'Classpath' Tab in the UI. It bypassed the computation of the correct classpath in our launch configuration delegate. The incorrect result was then used to populate the 'default' value for the ui. Then adding extra folder to it ended up with an incorrect classpath which was then being saved.

I have adjusted how we handle the classpath computation so that it now yields the same correct result for classpath either via the launch configuration delegate or going directly to JDT's 'computeUnresolvedClasspath' method.

I think that should fix this bug.

**Comment by kdvolder** [comment]
BTW: Thanks for a great bug report with all the necessary details to figure out what exactly the problem was. I wish every bug report was like this one :-)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I tried this with the latest from master and using the sample project from the bug report. When I run the "boot-launcher broken" launch config with the empty folder on the classpath setting, the classpath that gets printed to the console is still different then the one from the standard launch and I can still see the test-classes being added, as described in this bug report. Am I missing something?

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Yes, that is expected. The 'broken' launcher attached to report is in fact broken. However the bug I fixed is what produced that broken launcher. Fixing the bug does not fix the broken launcher, it will only make it so, in the future, the same steps that produced the broken launcher will instead produce a correct launcher.

So you should instead try to create a launcher in the usual way. I.e. by running something from boot dashboard. Or via 'Run As >> Spring Boot App'.

Then modify that launcher by opening classpath tab and add empty folder.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

Ah, I see, okay. Tested again and works nicely that way... :-)

**Comment by bluebilt** [comment]
I can confirm that using the latest nightly build the problem is resolved, thanks Kris. :thumbsup:
For the fix, but also for the kind words about my bug report. :smirk:
