### ISSUE TITLE
Error occurring while collecting items to be installed

### ISSUE THREAD

**Issue by jzb3db** [spring-projects/spring-ide#153]
These two attempts to install the Spring IDE plugin were initiated behind a corporate proxy, although I did have the proxy configured in Eclipse.

1. Installing the plugin from Eclipse Marketplace is producing the following error message:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://dist.springsource.com/release/TOOLS/update/3.8.4.RELEASE/e4.6/plugins/org.springframework.ide.eclipse.config.core_3.8.4.201703310634-RELEASE.jar.
http://dist.springsource.com/release/TOOLS/update/3.8.4.RELEASE/e4.6/plugins/org.springframework.ide.eclipse.config.core_3.8.4.201703310634-RELEASE.jar

2. Trying to download the plugin from the link listed in the README (http://dist.springsource.com/release/TOOLS/update/e4.6) produces the following error:

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E6C0D7D6D0AB21FE</RequestId>
<HostId>VL6Rhv/Zy3RlXwnUh7LfwImrWWKeK2ofmTI1GLZrcA2jN2zNxeCmq9j+DlUC3zOV33QMBqGJW0s=</HostId>
</Error>`

Notes:
- I successfully installed other packages via Eclipse Marketplace, but still can't figure out what's up with the Spring IDE installation.
- I successfully installed the Spring IDE plugin at home on my personal computer without any problems. 

To do:
- Double check network settings in Eclipse. 
- Check antivirus and firewall settings.

**Comment by martinlippert** [comment]
With regards to 1.

It looks like an issue with stale or corrupted p2 cache data. I would recommend to startup Eclipse, go to the `Preferences -> Install/Update -> Available Update Sites` and remove the above mentioned update site. Then restart Eclipse and try again. This should wipe out the stale data and you should be fine installing the features.

Another way would be to go to the `Install New Software` dialog and use the update site manually from there and see if that solves the issue (maybe also after deleting the update site once).

With regards to 2.
http://dist.springsource.com/release/TOOLS/update/e4.6 is a URL for a p2 repository, which doesn't have or serve any index page. Therefore the server sends you back that mentioned AccessDenied message. Put that URL into your Eclipse via `Install New Software` and it should work.

**Comment by jzb3db** [comment]
Thanks! For anyone else who's run into this obstacle, I recommend following @martinlippert's comment. 

In my case, [McAfee SiteAdvisor Enterprise Plus](https://www.mcafee.com/us/products/siteadvisor-enterprise.aspx) was preventing Eclipse from downloading certain files. Specifically, McAfee thinks http://dist.springsource.com/release/TOOLS/update/3.8.4.RELEASE/e4.6/plugins/org.springframework.ide.eclipse.config.core_3.8.4.201703310634-RELEASE.jar behaves like a Trojan horse. 

So if you're at work and you're also having firewall/antivirus issues, you should probably contact your security team for help unless you're comfortable navigating around your browser security plugins.

**Comment by martinlippert** [comment]
Thanks for sharing the additional details.
