### ISSUE TITLE
STS 3.8.4 - error creating Spring Starter Project - JSONException

### ISSUE THREAD

**Issue by sudusan** [spring-projects/spring-ide#156]
I get an immediate error when i go to the New Spring Starter Project screen
JSONException: A JSONObject text must begin with '{' at character 1
Service URL: http://start.spring.io

Any help is appreciated
Regards,
Sudhakar

**Comment by martinlippert** [comment]
Maybe a network issue? If you continue pressing "Next" in the wizard, you will end up with a wizard page that shows you the exact http request that the tool will use against start.spring.io. You could try to copy/paste that into a browser to see if that works (to check where the issue might be located).

To workaround the problem, you can also go to the webpage of start.spring.io and use the web UI to select dependencies and options - and download a ZIP of the generated project at the end. You can then extract that ZIP file locally and import the generated project via "Import as existing Maven project" (in case you selected Maven).

**Comment by osmanddas** [comment]
Network speed was the main culprit in my case. It went down drastically and as a result I started getting this error. Later when I connected with a better network, the error message disappeared and I could successfully process with my work.

**Comment by martinlippert** [comment]
Ok, sounds good, thanks for letting us know. Closing this issue.

**Comment by dharm117x** [comment]
Change STS service url from http://start.spring.io to https://start.spring.io.
its should be fixed.

**Comment by Kuldeep-Rana** [comment]
@dharm117x  Thank you, using https:// worked for me.

**Comment by gauravgupta1234** [comment]
Change STS service url from http://start.spring.io to https://start.spring.io.
its should be fixed.

**Comment by Rincy-Cheriyan** [comment]
@dharm117x  Thanks.. using https:// worked for me

**Comment by Amirakhazri** [comment]
Just need to add "/ "
like 
https://start.spring.io/
