### ISSUE TITLE
Ctrl+Alt+↑ not duplicating line - Windows 7 

### ISSUE THREAD

**Issue by jbedenbaugh** [spring-projects/spring-ide#157]
Environment:

- Windows 7 Enterprise
-- Service Pack 1
 
- STS 
-- Version: 3.8.4.RELEASE
-- Build Id: 201703310918
-- Platform: Eclipse Mars.2 (4.5.2)

When using STS and attempting to duplicate a line of code, the Ctrl+Alt+↑ key sequence does not duplicate the line.

Please advise if this has been addressed.

**Comment by BoykoAlex** [comment]
`Ctrl-Alt-Up` key binding worked for me on Windows 10 with fresh installs:
- STS 3.8.4 on Mars
- STS 3.8.4 on Neon
- STS 3.9.0 on Neon
- STS 3.9.0 on Oxygen

This particular key binding comes from the Eclipse Platform itself and STS doesn't seem to alter it. If you've installed other plugins on top os STS then there might be key binding conflicting with this one. Check `Preferences -> Keys` page to resolve any conflicts. Also try a fresh STS install without any plugins installed on top of it.

**Comment by jbedenbaugh** [comment]
Thanks for that. Not sure if the plugins are a problem - I have pretty standard stuff installed. I'm thinking it could be all the corporate spyware installed by the company, but I'll have to check to see if there is an intercept - or it could just be Windows 7 - although a search doesn't yield any results (Ubuntu had this problem reported some years ago). Thanks for checking though.
