### ISSUE TITLE
STS 3.9.0 Spring Boot Fast startup and extra VM args error

### ISSUE THREAD

**Issue by gigermocas** [spring-projects/spring-ide#159]
Fast startup's  VM args are being concatenated with no separators to any existing VM argument defined in the Spring Boot App's Arguments tab.
In my case I have a VM arguments value of "-javaagent:spring-instrument.jar", and the resulting error when I try to run the Boot App with Fast startup enabled is:
`Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : spring-instrument.jar-noverify`

VM arguments are trimmed so only option is to disable Fast startup.

**Comment by martinlippert** [comment]
Arg... That is too bad... Will put this in the list things to fix in 3.9.1 immediately.
