### ISSUE TITLE
Subversive connector discovery not working; need to manually install connector instead

### ISSUE THREAD

**Issue by tomlprog** [spring-projects/spring-ide#165]
In previous versions of STS Subversive SNV connectors could be easily installed via the Subversive connector discovery dialog.  In this version (3.9) the dialog displays and you can select one of more connectors, but the connectors do not actually get installed.  As a work-around you need to install the following update site: Subversive Neon Site - http://community.polarion.com/projects/subversive/download/eclipse/6.0/neon-site/
and then install the connectors using Help->Install New Software

**Comment by martinlippert** [comment]
Looks like a problem that is very specific to the Subversive extension. I would recommend to report this to the Subversive project to get the install problem fixed.
