### ISSUE TITLE
Starting Run/Debug Config with JVM parameter results in jar errors

### ISSUE THREAD

**Issue by ydalley** [spring-projects/spring-ide#168]
I just updated STS to

Spring Tool Suite 
Version: 3.9.0.RELEASE
Build Id: 201707061903

I realized that JVM parameters  I pass are resulting in errors
`
Error opening zip file or JAR manifest missing : /Users/xxxx/.m2/repository/org/aspectj/aspectjweaver/1.8.10/aspectjweaver-1.8.10.jar-noverify
Error occurred during initialization of VM
agent library failed to init: instrument`

I seems -noverify is appended  to VM parameters when initiating a run configuration from the IDE.

**Comment by kdvolder** [comment]
Rigth... its been reported already: #159 But thanks for the report. Better to have several reports of a bug than none at all :-)

**Comment by martinlippert** [comment]
(please note that the easy workaround for this is to disable the fast startup option in the preferences)

**Comment by uruloki85** [comment]
@martinlippert I can't find this option in the preferences. Could you elaborate, please?

**Comment by ydalley** [comment]
![screen](https://user-images.githubusercontent.com/26444020/28268020-810188d4-6af4-11e7-965d-dc7baa5011aa.png)

**Comment by uruloki85** [comment]
Thanks! I already found it but in a different place (if you remove the VM arguments here it will be applied to all your projects):
![image](https://user-images.githubusercontent.com/6115564/28268164-7e863844-6afd-11e7-8391-8e386cc5b349.png)

**Comment by martinlippert** [comment]
Yes, that was the piece (in the preferences) I was referring to... :-) Glad to hear you found it. Was in a hurry, otherwise I would have added the exact path the right right preference. Sorry for that.
