### ISSUE TITLE
Spring start project fails in STS with spring boot 1.5.4

### ISSUE THREAD

**Issue by gulliver-smith** [spring-projects/spring-ide#170]
I have a version of STS that I have been using for a Spring boot (1.4.1) project for almost a year.

I ran check for updates and updated everything in STS.

An attempt to create a new spring boot project with "New Spring Starter Project" fails.

Error messages include
```Description	Resource	Path	Location	Type
The project was not built since its build path is incomplete. Cannot find the class file for org.springframework.context.ConfigurableApplicationContext. Fix the build path then try building this project	demo		Unknown	Java Problem
```
and
```Description	Resource	Path	Location	Type
The type org.springframework.context.ConfigurableApplicationContext cannot be resolved. It is indirectly referenced from required .class files	DemoApplication.java	/demo/src/main/java/com/palominosys/demo	line 10	Java Problem
```

Similar problems when trying to upgrade my 1.4.1 project to 1.5.4, Reverting back to 1.4.1 works fine. In debugging I cleaned out the maven .m2/repository, but this made no difference.

**Comment by gulliver-smith** [comment]
More strangeness - completely new download of STS on Windows 10. Pull existing working project from github.

Project will not build 

```Description	Resource	Path	Location	Type
The project was not built since its build path is incomplete. Cannot find the class file for javax.servlet.ServletException. Fix the build path then try building this project	project1		Unknown	Java Problem
```

**Comment by martinlippert** [comment]
What happens if you go to the context-menu on the project, then `Maven -> Update Project...`?
That usually helps me in your situations where Maven is complaining about the project setup.

**Comment by martinlippert** [comment]
Any news on this? Did the project update help? Or is this still an issue?

**Comment by codenat13** [comment]
I am having a similar problem. I am using Version: Oxygen.1a Release (4.7.1a) and STS 3.9.1
I am following a tutorial to integrate angular. I created a SpringBoot Web server project to which I didn't add or change much.  And the first time I try to build, it shows:

> The type org.springframework.context.ConfigurableApplicationContext cannot be resolved. It is indirectly referenced from required .class files

It is referencing the following:
```
@SpringBootApplication
public class SpringBootAngular4Application {

	public static void main(String[] args) {
		SpringApplication.run(SpringBootAngular4Application.class, args);
	}
}
```
I tried @martinlippert 's solution of
> What happens if you go to the context-menu on the project, then Maven -> Update Project...?
> That usually helps me in your situations where Maven is complaining about the project setup.

The error disappeared ... until I tried building it again. Then it came back.
Any suggestions?

**Comment by martinlippert** [comment]
Maybe there is a problem with the JAR files in the local Maven repository. Try deleting the .m2/repository folder and hit `Maven -> Update Project...` another time to trigger Maven to download the dependencies again.

**Comment by codenat13** [comment]
I tried a solution I found on stackoverflow. It seems to have worked. It is similar to what you just suggested. 👍 

> Your maven cache is corrupted. To resolve this problem, follow the steps below:
> 
> Go to the directory of your project on the command line.
> Make sure your POM.xml is in the same directory as your command line
> Run the command
> mvn dependency:purge-local-repository
> If you receive build successful message, means the error has been resolved.
> If error is still there, delete your (~/.m2/repository/org/springframework) folder and run
> mvn package
> It will work properly now.

**Comment by martinlippert** [comment]
Good to hear that you got it working again. And thanks for letting us know.

**Comment by Neeharika17** [comment]
Hello all,
I am getting the same error.But unable to run the command mvn dependency:purge-local-repository and also where can I find the ~/.m2/repository/org/springframework to delete.

**Comment by martinlippert** [comment]
@Neeharika17 you can't find the local maven repository? what system are you running on?

**Comment by ajeet0203** [comment]
.m2\repository\org\springframework\boot\ and deleted everything 
and again open sts and goto maven update and done

**Comment by pmverma** [comment]
@codenat13 Thanks, deleting the ~/.m2/repository/org/springframework helps it!
