### ISSUE TITLE
Replace icons with HiDPI-Versions

### ISSUE THREAD

**Issue by davidbilge** [spring-projects/spring-ide#173]
On a HiDPI-Monitor (i.e. with Windows 10 scaling set to something higher than 100%), most toolbar icons in Eclipse look great - except for those that belong to STS.

I'm using STS 3.9.0 on Eclipse Oxygen.

![sts-lowres-icons](https://user-images.githubusercontent.com/762988/28358089-d721dc26-6c6d-11e7-8e2d-a80b0bd219f0.png)

**Comment by martinlippert** [comment]
Yes, agree. Will put this in the list for 3.9.1

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I've integrated high-res images for those icons as a first step. We are still far away from having everything in high-res, but it is start. I will close this one as done, but we will keep adding more and more high-res icons over time.
