### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by mhddurrah** [spring-projects/spring-ide#174]
**URGENT**

I am using linux mint 18.2 / 64-bit
java version: Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
when I start STS and in splash it reaches the loading org.eclipse.oomph.setup.ui i closes immediately
I have to remove the .metadata folder and reimport projects
attached is the log file located in workspace .metadata folder

[log.txt](https://github.com/spring-projects/spring-ide/files/1163101/log.txt)

**Comment by martinlippert** [comment]
Just to make sure I understand you correctly: if you start STS with a fresh workspace, it starts up just fine?

There is no immediately solution that comes to my mind when looking through your log file, therefore maybe the "start with a fresh" is the best solution at the moment.

**Comment by mhddurrah** [comment]
Hello,
if I start with a fresh workspace and import my projects into it, then I shutdown my computer -or sometimes even closing the IDE- it gives the same behaviour. it makes me re-import my projects every time I start it :smile: , I have returned to older 4.8.3 version.

**Comment by martinlippert** [comment]
Wonder if using a plain Eclipse Oxygen JEE distro would change that behavior or not. In case you want to give it a try (for diagnosing the issue only), I would certainly be interested in hearing about those experiments.

**Comment by mhddurrah** [comment]
Thank you @martinlippert , I did what you suggest and it seems to work well, I got an updated version of eclipse with sts features :+1:

**Comment by martinlippert** [comment]
Great to hear that you got things working again. Glad I could help.
