### ISSUE TITLE
Not possible to create new project using Gradle: Buildship not recognized

### ISSUE THREAD

**Issue by batterista87** [spring-projects/spring-ide#175]
Hello, I've this error when creating a new project using Gradle:

> Can not import using Gradle (Buildship 2.x) because Buildship Gradle Tooling version 2.x is not installed. You can install it from Eclipse Marketplace.

Here the opened bug on StackOverflow.
https://stackoverflow.com/questions/45376675/spring-tool-suite-not-possible-to-create-new-project-with-gradle-can-not-import

Thanks

**Comment by kdvolder** [comment]
It has been reported before and fixed. See: #163

**Comment by martinlippert** [comment]
Buildship 2.1.2 got released and works nicely again with STS 3.9.0.

**Comment by batterista87** [comment]
Solved. Thanks.
