### ISSUE TITLE
Eclemma Plugin new version has a new name

### ISSUE THREAD

**Issue by krugiesv** [spring-projects/spring-ide#177]
As the Title may or may not show, the Java Code Coverage Plugin Eclemma has a new distribution name. 
Since Eclipse 4.7 (Oxygen) it is "under the umbrella of the Eclipse Foundation" (http://www.eclemma.org/changes.html) and therefore has changed its Updatesite a little bit. Instead of com.mountainminds.eclemma.feature.feature.group it is now org.eclipse.eclemma.feature.feature.group. 
STS (v. 3.9.0) is looking for the old pluginname to implement it into the STS-perspective, but can not find anything, as the nonappearance of the button suggests. 

The corrsponding part in your code may be:  spring-ide/plugins/org.springframework.ide.eclipse.ui/src/org/springframework/ide/eclipse/ui/SpringUIPlugin.java
Line 60 onwards.

Thanks for looking into it.

**Comment by martinlippert** [comment]
Thanks for reporting this, much appreciated. Fixed now. The new bundle ID is now taken into account, works with both the old and the new EclEmma IDs.
