### ISSUE TITLE
The Compressed (Zipped) Folder .... is invalid

### ISSUE THREAD

**Issue by BholaAnil** [spring-projects/spring-ide#178]
I downloaded the Zip File "spring-tool-suite-3.9.0.RELEASE-e4.7.0-win32-x86_64" spring.io/tools/sts site. 

after downloading when I tried to extract i am getting "The Compressed (Zipped) Folder .... is invalid"

Can you please help me how I can download clean zip files ?

thanks
Anil Bhola

**Comment by kdvolder** [comment]
I tried to download it just now and unzipped fine for me. So I'm not really sure why you can't.

I have two possible guesses: 

1. Maybe you need to use a proper zip program. I've heard from some folks that using the unzip facility built-in to windows often doesn't work. So maybe try to use 7zip or winzip instead. 

2. If that also doesn't work, perhaps something in your network environment is interfering with the downloads. This is especially likely if you are on a corporate network where various network management processes may in effect and they are somehow stopping your from downloading the zips.

I'll close this ticket as it doesn't seem to be a problem on our end.

**Comment by kdvolder** [comment]
Third guess :-)

3. Maybe it was a temporary problem, something causing a corrupted download. You could try re-downloading it again.

**Comment by martinlippert** [comment]
Here is the download link again:
http://download.springsource.com/release/STS/3.9.0.RELEASE/dist/e4.7/spring-tool-suite-3.9.0.RELEASE-e4.7.0-win32-x86_64.zip

Here is the MD5 for verifying the downloaded file:
http://dist.springsource.com/release/STS/3.9.0.RELEASE/dist/e4.7/spring-tool-suite-3.9.0.RELEASE-e4.7.0-win32-x86_64.zip.md5

That way you can find out whether you got the correct file or something got corrupted along the way (as Kris mentioned, some proxies and firewalls might have issues with large zip files that contain executables for Windows).
