### ISSUE TITLE
STS 3.9.0.RELEASE: Autocompletion for JPA CrudRepository doesn't work..

### ISSUE THREAD

**Issue by OllisGit** [spring-projects/spring-ide#179]
... if you use "Completion overwrites" in "Java / Editor / Content Assist".
With the default Eclipse Setting "Completion Inserts" everything works fine, when doing "completion" in 
repository methodenames.  You select an Entity-Attribute (from the popup) and the fieldname is insert into the methodename.

But if you use "Completion overwrites" and
- Create a new CrudInterface (extends CrudRepository<MyEntity, Long>)
- Add a methode like: public MyEntity findBy(), place the cursor before () and do a codecompletion
- Select a field -> nothing is inserted

Or
- Create a new CrudInterface (extends CrudRepository<MyEntity, Long>)
- Add several finder-Methods with JavaDoc in it
- Place the cursor to the first finder and do a codecompletion
- Select a field -> the followed javadoc withe the method is gone
BUT the fieldname is inserted ;-)

Thx, in advance for your support
Olli

**Comment by martinlippert** [comment]
This sounds very much like a bug in the code completion for Spring Data... :-) Will put this on the list of things to fix for 3.9.1. Thanks for pointing us at this.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

I've taken a look at this, I unfortunately have not been able to come up with a solution that works with "Completion Overwrites" preference for 3.9.1. Would have to spend more time in the future for this, probably post 3.9.1

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I took another look at this and the problem was the computed replacement length, which wasn't correct. This value isn't taken into account by JDT when you have the "completion inserts" setting, but it is the important piece for "completion overrides". This is fixed now.
