### ISSUE TITLE
Cannot install groovy-eclipse because STS installation directory is read-only

### ISSUE THREAD

**Issue by mangelo123** [spring-projects/spring-ide#183]
I initially installed into ~/ and then moved to Documents to see if that made a difference and it does not.

**Comment by martinlippert** [comment]
How did you try to install Groovy-Eclipse? And what version of STS are you running? On which system?

**Comment by mangelo123** [comment]
I was trying to install on MacOS - Sierra. The only way that I could is if I ran STS by going into the directory: sts-bundle-3.9/STS.app/Contents/MacOS and then running with ./STS

I could then install the groovy eclipse extension. 

Originally, I tried from the IDE extensions section.

**Comment by martinlippert** [comment]
Maybe you run into this issue:
https://stackoverflow.com/questions/40724146/sts-app-on-mac-10-12-1-always-creates-a-new-org-springsource-sts-folder-in-ecli

It sounds very much related (read-only and a translocated app). And running STS via the ./STS from the command line avoids the app translocation of macOS.

Can you try the solution and move the STS.app to a different location after you extracted it - and use the Finder (drag&drop) for it, not the command line.

You can also double-check if your STS install runs as a translocated app by looking through the configuration details (via the About dialog). Some system properties for the runtime suddenly contain some random paths, including the "AppTranslocation" string.

Can you verify and let us know if that fixes the install issue for you?

**Comment by mangelo123** [comment]
I uncompressed the archive, moved the folder to my home directory and got the same issue. I moved it to Documents and no different. I moved only STS.app back to my home directory, and the options were no longer disabled. How should I proceed?

**Comment by martinlippert** [comment]
Not sure what you mean by "and the options were no longer disabled"?!?

You need to move the STS.app (not the folder) to a different location using Finder. Moving the complete folder doesn't help.

**Comment by mangelo123** [comment]
The options to install the groovy eclipse options are disabled unless I move the STS.app file only. If I move the entire folder, they are disabled.

**Comment by martinlippert** [comment]
Okay, understand. Sounds like after moving the STS.app itself into a new location via Finder, everything is fine again, right? Okay to close the issue here or is there anything left?

**Comment by mangelo123** [comment]
So, its ok to run STS.app outside of the sts-bundle folder? If that is the case, then we can close this out.

**Comment by martinlippert** [comment]
Yeah, of course it is perfectly fine to run STS.app outside of the sts-bundle folder.

You will not get the tc-server instance configured automatically inside of STS when it is not close to the STS.app, but you can configure it manually any time from any location on your disc.
