### ISSUE TITLE
STS installation problem.  java was started but returned exitcode 13

### ISSUE THREAD

**Issue by dhiraj1125** [spring-projects/spring-ide#184]
I am trying to install STS 3.9.0 64 bit in my HP Laptop, but I am getting error- java was started but returned exitcode 13
I googled it and found everything should be either 64 bit or 32 bit combination. I cross checked it and found Spring+java+OS all are 64 bit. 
I am using eclipse neon in this machine without any hassle.
I have windows 8.1 OS installed in my machine.
![stsc](https://user-images.githubusercontent.com/4905005/29647896-28f0c182-88a9-11e7-8fea-dd30c07557af.png)

I already spend 3 days in this, I am loosing my patience Any help will be highly appreciated

**Comment by martinlippert** [comment]
This looks very much like a problem with mixed 32bit and 64bit runtimes. The STS build seems to be the 64bit one. Are you sure that the Java version that runs at C:\Program Files\Java\jre1.8.0_131 is the 64bit version?

I would also recommend to define a full-blown JDK as the runtime (instead of the JRE only) by modifying the STS.ini file with an additional vm arg right at the beginning, as explained in this doc: https://wiki.eclipse.org/Eclipse.ini.
Please keep in mind that the "-vm" line has to be the first line in that file, followed by an additional like containing the path to the 64bit JDK.

Hope this helps!!!

**Comment by martinlippert** [comment]
Any news on this? Does it work now?

**Comment by dhiraj1125** [comment]
I tried but I am not able to fix it, Now I am working on eclipse+sts plugin. I have tried a lot to fix that but I could not able.

**Comment by martinlippert** [comment]
I am wondering why Eclipse Oxygen works out of the box, but STS does not (if I understood this correctly). Both use the same launcher code to identify the JVM to run with.

Can you post your STS.ini file that you tried?

**Comment by dhiraj1125** [comment]
-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.500.v20170531-1133
-product
org.springsource.sts.ide
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms40m
-Dosgi.module.lock.timeout=10
-Xverify:none
-Dorg.eclipse.swt.browser.IEVersion=10001
-Xmx1200m

**Comment by martinlippert** [comment]
That looks like a regular STS.ini file without any modifications. Where do you have your 64bit JDK installed on your machine? What happens if you modify your STS.ini file and add those "-vm" arguments to it, like described here: https://wiki.eclipse.org/Eclipse.ini#-vm_value:_Windows_Example ?!?

**Comment by m-michalko** [comment]
Hello,

Sorry to hijack the thread but I am getting the same error.
Downloaded and unpacked sts bundle 3.9.0 (download page does not specify if it is 32 or 64bit)

After launching STS got the error 13 dialog box.
Modified STS to point to 64 bit java instalation

-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_1.1.500.v20170531-1133
-product
org.springsource.sts.ide
--launcher.defaultAction
openFile
-vm 
C:\Program Files\Java\jdk1.8.0_144\bin\javaw.exe
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms40m
-Dosgi.module.lock.timeout=10
-Xverify:none
-Dorg.eclipse.swt.browser.IEVersion=10001
-Xmx768m

Again the same error. (tried path in quotes and w/o quotes)
Checked Java version:
C:\Program Files\Java\jdk1.8.0_144\bin>java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Still getting the same error.
Do I overlook some stupid detail? 
Please Help :)

Thanks a lot

**Comment by YogitaRana** [comment]
From yesterday also I was facing the same problem even though having the same Java version 8 of 64 bit and the STS of 64 bit .I just have removed the -vm entry fromthe STS.ini file and it worked.

You just need to set the path of JDK in the environment variable and just start your STS

Will work !

**Comment by martinlippert** [comment]
@m-michalko you seem to have a 64bit JDK installed, but trying to run the 32bit version of STS. In addition to that please note that the -vm argument in the ini file should be the first one on that file, not somewhere in between.

**Comment by jjerezalo** [comment]
It depends on your development environment, if you installed JDK x64, you must install STS x64 that can be downloaded [here](http://download.springsource.com/release/STS/3.9.1.RELEASE/dist/e4.7/spring-tool-suite-3.9.1.RELEASE-e4.7.1a-win32-x86_64.zip). Other version/systems [here](https://spring.io/tools/sts/all).

**Comment by bimleshaws** [comment]
I'm facing this issue when installing STS4 
error:could not create the java virtual machine.
error:a fettal exception occurred. program will exit.
please help in same..

**Comment by bimleshaws** [comment]
i have installed jdk 64 bit and STS4 is also 64 bit but eclipse is 32 bit

**Comment by martinlippert** [comment]
If you have a 64bit JDK installed and a 64bit STS4 for Eclipse distribution, it should all be fine. Maybe, in case you have multiple versions of the JDK installed (or both, the 32bit and the 64bit version), you should tell STS4 which JDK to use in the SpringToolSuite4.ini file (as described above). That should point STS4 to the right JDK.

I am not sure why you mention a 32bit Eclipse install here, that sounds unrelated - at least in case you downloaded a ready-to-use STS4 distribution (and haven't installed as add-on into an existing Eclipse install).

**Comment by notoneword** [comment]
I was running into a wall with this issue until I removed the Oracle/**/javapath entry from my %PATH%.  At some point I had upgraded to Java 13 while still trying to use the java 1.8 JDK.  My JAVA_HOME was pointing at JDK-13 as well.  I changed JAVA_HOME to the 1.8.0_221 location and removed the Oracle*javapath value (Sorry, can't find the exact location, but if you see it as the top entry of your PATH, you should try removing it, it helped me.)

**Comment by martinlippert** [comment]
@notoneword Thanks for sharing your experiences here with the community. I am sure that others will benefit. Much appreciated!

**Comment by sakthikanth** [comment]
I have added following two lines in configuration file on first line
-vm 
C:\\Path to Java\jdk-13.0.1\bin\javaw.exe

And i have deleted oracle home paths which i have already installed.
This works for me.Thanks
