### ISSUE TITLE
Quick Search doesn't show in preferences or key bindings screen after installation

### ISSUE THREAD

**Issue by Krakkow** [spring-projects/spring-ide#186]
So I installed the plug-in separately from the STS package and tried to install it also with it.
But although eclipse sas this plug-in was installed, I still can't use it, can't find, can't do anything with it.

I'm using eclipse mars 4.5.2 on a windows 10 x64bit machine.

Please help.

**Comment by martinlippert** [comment]
@Krakkow So the install went fine, but you can't invoke it? The dialog doesn't come up? Maybe there is a keybinding conflict. Can you check via the Preferences?

**Comment by Krakkow** [comment]
@martinlippert Yes. The installation went fine. I can also see the jars in the plugins folder of eclipse. But Quick Search is nowhere to be found. Not in the preferences main menu nor in the Key binding table\list.

How can I help you figure this out?

**Comment by kdvolder** [comment]
Try this: 

1. Open "window >> preferences" . In search box at top type 'quick search'. Not showing? (Yes, I think you said that already, just making sure / double-checking  you are looking in the right place).

If it does show in 1... then, likely there's some keybinding conflict. Then try '2.' Otherwise probably something is conflicting with bundle activation, then try '3.'.

2. "Window >> preferences". Search for "Keys". Then in the keys prefs page's search box type "quick search". Find the 'Quick Search Command' and try modifying its key bindings.

3. Windows >> Show View >> Other >> Error Log. Then look for any signs that osgi is failing to load some bundles (because of dependency/incompatibility issues)

**Comment by Krakkow** [comment]
Hey @kdvolder Thanks!
I went over the steps. Your hunch was right on the money with the error log. 
I'm sending the Exception Stack Trace and the Session Data, maybe you could figure it out and tell me what requirements are missing.

**Exception Stack Trace**
`org.osgi.framework.BundleException: Could not resolve module: org.springsource.ide.eclipse.commons.quicksearch [975]
  Unresolved requirement: Require-Bundle: org.springsource.ide.eclipse.commons.livexp
    -> Bundle-SymbolicName: org.springsource.ide.eclipse.commons.livexp; bundle-version="3.8.4.201703310458-RELEASE"
       org.springsource.ide.eclipse.commons.livexp [974]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)`

**Session Data**
`eclipse.buildId=4.5.2.M20160212-1500
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data file:/C:/Users/ork/workspace/ -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product
`

Put the stacks in code mode so they'll be easy to separate from the message text. 👍

**Comment by Krakkow** [comment]
I can also tell that this problem is recurring in more the one PC we use on our team.

**Comment by Krakkow** [comment]
**SOLVED**

The issue was the JRE I had on the machine. 
I had JAVA 7 and the plug-in requires JAVA 8.

Thank you.

**Comment by martinlippert** [comment]
Yes, looks like you ran on a JDK7 or older and the plugin needs JDK8. But why did you re-open the issue?

**Comment by Krakkow** [comment]
I didn't thought I'm the to close it :) 
I'll close it now. :)

**Comment by martinlippert** [comment]
Great, thanks. And glad to hear it is working now!!!
