### ISSUE TITLE
use AmaterasUML in sts?

### ISSUE THREAD

**Issue by xiluhua** [spring-projects/spring-ide#188]
Graphical Viewers and Editors

Want to get an overview of the bean dependencies in your Spring app? Or wanna visualize and edit Spring Integration, Spring Batch, or Spring Webflow definitions? Check out the graphical editors that come with the Spring Tool Suite, right in your IDE, just one click away from your configuration files.

this is a introduction in https://spring.io/tools/sts
but the how-to is not available.
could someone gives some hint?

**Comment by xiluhua** [comment]
ok, i get the answer myself:

1. download AmaterasUML.zip from url below
https://osdn.net/projects/amateras/downloads/56447/AmaterasUML_1.3.4.zip/

2. unzip and put the jars into sts plugins folder
like this: F:\work2017\eclipse4\sts-bundle\sts-3.8.4.RELEASE\plugins

3. restart the sts

4. file --> new --> other --> AmaterasUML 

done!

**Comment by kdvolder** [comment]
Thanks for that, maybe it is helpful to someone, but I should make clear to anyone reading this that STS does not have any relationship to AmaterasUML editor, and we do not in any way endorse its use. Please proceed with caution and install at your own risk.

The graphical UML-like view that Xiluhua is likely referring to is available in STS only for old-style legacy projects that use the old-fashioned XML bean configuration format. If anyone is wondering how you open that view, which is built-in to STS and doesn't require you to install any additional software. It goes as follows:

1. open your XML config file by double clicking it.
2. Select the 'Beans Graph' tab on the right.

A graphical representation of the beans defined in that XML file will then be shown.
