### ISSUE TITLE
Unable to work on Spring Security using Eclipse STS?

### ISSUE THREAD

**Issue by Satyataken** [spring-projects/spring-ide#189]
I am not able to work on Eclipse STS while trying to implement Sring Security in my spring boot application. It is giving some strange error at compile time. Attaching the code : 
[SpringWebAngularJS.zip](https://github.com/spring-projects/spring-ide/files/1292122/SpringWebAngularJS.zip)
STS version  :  **spring-tool-suite-3.9.0.RELEASE-e4.7.0-win32-x86_64**
For more details visit same on [stackoverflow.](https://stackoverflow.com/questions/45961925/unable-to-work-on-spring-security-using-eclipse-sts/45997489?noredirect=1#comment79225754_45997489)

Upload again. Please try again.

**Comment by martinlippert** [comment]
@Satyataken doesn't seem to be a valid ZIP archive, can't unzip it properly. Can you try again or share the project on GitHub?

**Comment by Satyataken** [comment]
@martinlippert uploaded the ZIP file again. Please try again.

**Comment by martinlippert** [comment]
ZIP file works now. I can successfully import your project into my fresh STS 3.9.0 install and it compiles just fine. No issues appear. Maybe your local Maven repo contains corrupt or outdated versions of the libraries. I would recommend to delete the local Maven cache (~/.m2/repository) and do an "Maven -> Update Project" afterwards, maybe selecting the "force download of snapshots and releases" checkbox. Can you give that a try?

**Comment by Satyataken** [comment]
@martinlippert thanks for your effort and suggestion, the issue is resolved now.

**Comment by martinlippert** [comment]
Ok, will close the issue then. Glad to hear it is working again. What exactly solved the issue?

**Comment by Satyataken** [comment]
I just delete all the jars of from maven and rebuild the project. I really don't have any idea what was going wrong. Thanks a lot, without your help, I may not able to tackle this problem.

**Comment by martinlippert** [comment]
Glad to hear we could help.
