### ISSUE TITLE
IDE support for profile specific application.properties

### ISSUE THREAD

**Issue by beatjost** [spring-projects/spring-ide#190]
Me as a programmer would like to have also the auto-completion support for profile specific application.properties to edit those files similar to the default properties.

**Example:** application-local.properties

![image](https://user-images.githubusercontent.com/7138344/30310737-3cf7e460-9792-11e7-8364-ab9158ac0a84.png)

**Comment by martinlippert** [comment]
You can choose to open the `application-local.properties` file with the properties editor via the context-menu -> `Open With` and then choose the `Spring Properties Editor`.

In addition to that future versions of Eclipse will allow us to be more precise on the file name patterns that trigger the auto-selection of the properties editor, but that will happen in Eclipse 4.8.

**Comment by beatjost** [comment]
@martinlippert thanks a lot - works!
