### ISSUE TITLE
Global settings from spring boot devtools not being picked up from .spring-boot-devtools.properties on Windows 

### ISSUE THREAD

**Issue by diegoariashalfaker** [spring-projects/spring-ide#191]
I have enabled devtools on spring tools suite on my spring boot project on a windows machine. I have created a .spring-boot-devtools.properties with a simple property so that it reflects across all work spaces.
The file was placed in the C:\Users\user1 folder, but property is not being picked up in the application. If property is passed as jvm parameter app works fine.
I'm using STS 3.8.4
JDK 1.8.0_144
OS windows 10

**Comment by kdvolder** [comment]
And I assume it does pick this up if you run the app from the commandline?

**Comment by diegoariashalfaker** [comment]
Only if I pass the property as a jvm parameter. Property file is not picked even if I run from cmd

**Comment by kdvolder** [comment]
Thanks for closing the ticket. I think its the right thing to do as it doesn't seem to be a problem caused by STS. It might be worth raising a bug against Spring boot devtools, if you didn't do this already.

**Comment by diegoariashalfaker** [comment]
It was actually an issue on my side, so everything looks good now. thanks
