### ISSUE TITLE
Existing Eclipse Download link broken

### ISSUE THREAD

**Issue by Heidi-567** [spring-projects/spring-ide#192]
I am trying to download STS in an existing Eclipse installation, but the link on your page (https://spring.io/tools/sts/all) is broken. Where can I download a zip file for this?

extract from https://spring.io/tools/sts/all:
Update Sites
If you want to install STS in an existing Eclipse installation, you can use one of the following update sites. Please choose the one that matches the Eclipse version you're running: 

Eclipse - 4.7  http://dist.springsource.com/release/TOOLS/update/e4.7/

**Comment by martinlippert** [comment]
The full distribution downloads from https://spring.io/tools/sts/all work for me. You can go there, select the dropdown icon right next to the "Based on Eclipse 4.7.0" text and there you get the download link. I have to admit, the links are somewhat hidden that way... :-)

If you want to start with a plain Eclipse installation, you can go to the Eclipse Marketplace from within Eclipse, search for Spring or Spring Tools, and select the "Spring Tools" item to install. That provides you with all the Spring Tools goodness.

You could also choose the "Install New Software" and use the update site repo URL that you mentioned to install the components manually.

Hope this helps!!!

**Comment by Heidi-567** [comment]
Thanks Martin, I am looking to download a zip file of the Eclipse Oxygen Spring Tools plugin, as I need to install offline. I am unable to use Marketplace.
Thanks.

**Comment by martinlippert** [comment]
You can download the ZIP file of the p2 update repository here:
http://download.springsource.com/release/TOOLS/update/3.9.0.RELEASE/e4.7/springsource-tool-suite-3.9.0.RELEASE-e4.7.0-updatesite.zip

But you should be aware of the fact that the Spring Tooling needs specific things from the Eclipse Oxygen release repository when installing. That is installed by default in your Eclipse Oxygen install, but it means that during the install of the Spring Tools components, Eclipse has to contact the main Oxygen release repository and download artifacts from there. If you can't do that online, you might need to take care of having those components available offline, too.

But you could give it a try and install the pieces that you want from the Spring Tools archive - and see if something is missing and if so, what that piece is.
