### ISSUE TITLE
Organize Imports not working in latest version

### ISSUE THREAD

**Issue by StephenDillon** [spring-projects/spring-ide#195]
Cntrl + Shift + O no longer organizes imports with a fresh install on windows 10 for java projects.

**Comment by kdvolder** [comment]
Is it this: https://stackoverflow.com/questions/45085310/organize-imports-shortcut-not-working-after-sts-update/45087158#45087158

I beleave it is, if so, that bug has been reported and fixed a while back.

**Comment by StephenDillon** [comment]
Yeap that works thanks.
