### ISSUE TITLE
No space introduced before the "-noverify" when selecting "Fast startup"

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/spring-ide#197]
I noticed a small issue in the Eclipse plugin: 

If you have VM arguments already defined like "-Djava.security.egd=file:/dev/./urandom" and you then select "Fast startup" there is no space between the arguments and the "-noverify" : 

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java
-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=61423
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Djava.rmi.server.hostname=localhost
-Dspring.application.admin.enabled=true
-Djava.security.egd=file:/dev/./urandom-noverify
-XX:TieredStopAtLevel=1
-Dfile.encoding=UTF-8
```

This ends up still running because the error is "swallowed" as part of the "urandom" property. If you introduce any additional arguments (like "-Xmx"), the VM will fail to start.

**Comment by BoykoAlex** [comment]
Which version of STS are you using? Think we've fixed this already for STS 3.9.0...

**Comment by tkvangorder** [comment]
According to the Eclipse Installation Details:

```
Spring IDE Core (required)	3.9.0.201707061730-RELEASE	org.springframework.ide.eclipse.feature.feature.group	Spring IDE Developers
```

**Comment by BoykoAlex** [comment]
My bad it's in 3.9.1 that hasn't been released yet... You can either disable fast startup in the preferences or install from the nightly update site http://dist.springframework.org/snapshot/IDE/nightly/

**Comment by martinlippert** [comment]
Closing this is a duplicate of #159
