### ISSUE TITLE
Quick Search: Cannot search in /bin folder

### ISSUE THREAD

**Issue by JanecekPetr** [spring-projects/spring-ide#201]
Quick Search consistently does not search in any of my `bin` folders. Which is a problem because they contain executable shell scripts that sometimes need a full-text search. It does not matter whether the folder is a Java package name, or a nested directory under `src/main/resources/bin` or even `src/assembly/bin`.

And yes, I removed `bin` from the ignored names, and even tried removing `.bin` from the ignored extensions: https://i.imgur.com/JRGqMA2.png

**Comment by martinlippert** [comment]
@kdvolder can you have a look?

**Comment by JanecekPetr** [comment]
A quick look revealed [this line](https://github.com/spring-projects/eclipse-integration-commons/blob/master/org.springsource.ide.eclipse.commons.quicksearch/src/org/springsource/ide/eclipse/commons/quicksearch/core/ResourceWalker.java#L115).

```
protected boolean ignore(IResource r) {
	String name = r.getName();
	if (name.startsWith(".")) {
		return true;
	}
	if (name.endsWith(".jar") || name.endsWith(".zip")) {
		return true;
	}
	if (name.equals("bin")) {
		return true;
	}
	return false;
}
```

Nooo :(. Because of this I missed a property in an executable script while renaming the property. Of course the script was not tested (because it was not changed and has always worked) and failed in prod.

**Comment by kdvolder** [comment]
Yep... that ignore method is a holdover from before the time when we made the ignore logic configurable via preferences. Its hard-coded logic is completely redundant and should be removed. I just pushed change to that effect.

https://github.com/spring-projects/eclipse-integration-commons/commit/31d5ab285323d57bc8550c8405c6d745c09f578c
