### ISSUE TITLE
Can't add breakpoints on some methods in STS 3.9.1

### ISSUE THREAD

**Issue by AlessandroC85** [spring-projects/spring-ide#203]
I have noticed that with STS 3.9.1 I can't add breakpoints in methods of classes used as Maven Dependencies.
With previous version (3.9.0) it worked perfectly.

Now I can add breakpoints only at class level (at the class declaration row), but not in methods body.

**Comment by AlessandroC85** [comment]
I have been forced to remove STS with App Cleaner (on Mac OS), then I have reinstalled it and it works again.

But this means that there is probably some bugs in the new version of Eclipse...

**Comment by martinlippert** [comment]
First of all, glad to hear that it is working again (therefore closing this issue now). If you come across this again, please comment and attach a same project that helps to reproduce the issue. Thanks!!!
