### ISSUE TITLE
Broken link in grails/groovy tool suite website

### ISSUE THREAD

**Issue by pikeview** [spring-projects/spring-ide#204]
Hi,
  The "limited time" link is broken. Please advise how do we keep upto date on groovy/grails on Eclipse Neon and Eclipse Oxyggen.

![image](https://user-images.githubusercontent.com/18240627/31602977-9bfa3344-b256-11e7-804c-40af0617da12.png)

broken link: https://blog.pivotal.io/pivotal/news-2/groovy-2-4-and-grails-3-0-to-be-last-major-releases-under-pivotal-sponsorship

**Comment by martinlippert** [comment]
The correct and still working URL to that blog post is:

https://content.pivotal.io/blog/groovy-2-4-and-grails-3-0-to-be-last-major-releases-under-pivotal-sponsorship

And there is no version of the Groovy/Grails Tool Suite that is compatible with Eclipse Neon or Oxygen. The final release of the Groovy/Grails Tool Suite was released for Eclipse 4.5.

But the Groovy-Eclipse project got updated to recent versions of Eclipse. Please take a look at the corresponding wiki: https://github.com/groovy/groovy-eclipse/wiki.

**Comment by martinlippert** [comment]
I also submitted a pull request to fix the broken link on the tools page: https://github.com/spring-io/sagan/pull/790
