### ISSUE TITLE
eclemma plugin link (IDE Extensions) is invalid in 3.9.1

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-ide#205]
```
Problems occurred while performing installation: The following connectors are not available: EclEmma (id=com.mountainminds.eclemma.feature.feature.group, site=http://update.eclemma.org/)
The following connectors are not available: EclEmma (id=com.mountainminds.eclemma.feature.feature.group, site=http://update.eclemma.org/)
```

**Comment by kdvolder** [comment]
Confirmed. I.e. I tried install Eclemma from the 'Extensions' page and also got that error.

**Comment by kdvolder** [comment]
I was able to install Eclemma manually from this update site:
http://update.eclemma.org/

Also did a quick smoke test of Eclemma and it seems to work.

**Comment by kdvolder** [comment]
Looks like feature id has been changed. Pulled this from my workspace config after manual install:

org.eclipse.eclemma.feature (3.0.0.201706140232) "EclEmma UI"

**Comment by martinlippert** [comment]
Eclemma has been moved to Eclipse and is now available from the main Eclipse Oxygen update site. So the workaround is to use the `Install New Software` dialog, select the Oxygen site, search for Emma and select from there.

And we should update the extension install listing to use that update site and feature ID.

**Comment by martinlippert** [comment]
I also updated the item on the extension install to use the updated feature ID. Works again. And thanks for reporting, @garyrussell .
