### ISSUE TITLE
Gradle Buildship 2.0 and Subeclipse Plugins Disappear after Restart and Unable to Save Passwords

### ISSUE THREAD

**Issue by johnboyer** [spring-projects/spring-ide#212]
Everytime I restart STS, I have to reinstall the Gradle Buildship and Subeclipse plugins because they disappear.

Here's my build info:
_Spring Tool Suite 
Version: 3.9.1.RELEASE
Build Id: 201710111105
OS: Mac OS X, v.10.12.6, x86_64 / cocoa_

I'm also unable to save my SVN password. This seems like it might be permissions issue. Does anyone know what might be happening here?

Thanks, John

**Comment by BoykoAlex** [comment]
Try "Open Package Contents" on the STS package, navigate to `Contents/MacOS` and start STS from there.
Mac OSX starting from some version copies STS (or any other "unsigned" package from internet) to temp location and runs from there. Consequently any update done is gone after restart. I start it like i explained above and that leads to starting STS fro the location where it's placed originally and updates are persisted therefore.

**Comment by kdvolder** [comment]
Smells like the "Mac Os translocated my app" issue. See: https://stackoverflow.com/questions/40724146/sts-app-on-mac-10-12-1-always-creates-a-new-org-springsource-sts-folder-in-ecli

**Comment by johnboyer** [comment]
Yes, it was a Mac OS translocation issue, thanks. However, I'm still unable to get STS to store my passwords such as my SVN password. I'm always getting prompted even after I click Save Password in the Enter Username and Password dialog for the repository. Do you any ideas?

Thanks, John

**Comment by johnboyer** [comment]
The problem with password saving was associated with duplicate entries in Mac OS X Keychain Access, so I’m closing this issue. Thank your for your help!
