### ISSUE TITLE
Eclipse UI Thread freezes while Spring IDE Plugin creates Hyperlinks

### ISSUE THREAD

**Issue by SKuettner** [spring-projects/spring-ide#214]
I have >100 interdependent Maven/Spring projects in my workspace (~1.400.000 LOC) with hundrets of XML bean config files. When I open a class located in higher tier project (indirectly depends on >50 of the other projects) and press Ctrl (to access a context menu or to copy code via Ctrl+C) Eclipse freezes for 3s to 39s depending on which plugins are installed.

It originates from `org.springframework.ide.eclipse.quickfix.hyperlinks.AutowireHyperlinkDetector.addHyperlinks` (_see attached thread dumps created by Eclipse's built in monitoring_). It is reproducable with STS or an Eclipse for Java Developers with Spring IDE (just core) added.

Removing the Spring IDE completely solves the issue.

[eclipse_ui_freeze.log](https://github.com/spring-projects/spring-ide/files/1435632/eclipse_ui_freeze.log)
[eclipse_ui_freeze_1.log](https://github.com/spring-projects/spring-ide/files/1435633/eclipse_ui_freeze_1.log)

Might be related to [Bug 220585 - CElementHyperlinkDetector and DefaultCFoldingStructureProvider can block the UI thread](https://bugs.eclipse.org/bugs/show_bug.cgi?id=220585) 
or [Bug 376413 - Eclipse hangs on pressing Ctrl key, then displays a dropdown for View Declaration/View Implementation and resumes ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=376413)

I can't share the projects because our company doesn't allow it.

**Comment by martinlippert** [comment]
Thanks for the detailed report, much appreciated. This UI hang sounds really bad. I can see the AutowireHyperlinkDetector being involved there.

What happens if you disable that hyperlink provider via the preferences: `General -> Editors -> Text Editors -> Hyperlinking` ? Does it make things better with your large workspace?

**Comment by SKuettner** [comment]
This fixes my issue. Disabling the Autowire Hyperlink Detector removes the freezing completely. Thank you for this hint as I didn't know of this configuration and even didn't look for it!

**Comment by martinlippert** [comment]
Glad to hear that it works for you... :-)

**Comment by JanecekPetr** [comment]
(Still happening with Eclipse 4.19 and Spring IDE 3.9.16. My stacktraces are exactly the same. The workaround still works, thank you.)

**Comment by martinlippert** [comment]
I went ahead and disabled the Autowire Hyperlink Detector internally, so that it doesn't show up anymore and should not cause any of those issues again. This will ship as part of the next maintenance release (probably late June 2021).
