### ISSUE TITLE
Spring boot launch configuration: using the classpath tab still breaks the classpath

### ISSUE THREAD

**Issue by bluebilt** [spring-projects/spring-ide#222]
It seems that the fix for [issue 152](https://github.com/spring-projects/spring-ide/issues/152) does not cover all cases. Editing the classpath of an existing launch configuration works as expected now, but during creation of a new launch config the bug is still present.

Workaround: create the launch config without making any classpath changes, use it once, then edit it and make your required classpath changes.

**Comment by kdvolder** [comment]
Please provide detailed sequence of steps that still produce the bug. This is really helpful to us, please don't make us guess the steps based on a sketchy description. I.e. what I'm looking for is an exact sequence like:

1. Start STS in a new workspace
2. Click in menu X > Y > Z
...
=> Observe that XXX happens whereas YYY is expected.

**Comment by bluebilt** [comment]
Hi Kris,

The steps to reproduce the bug as well as a sample project were already in [issue](152) so I didn't expect much more info to be needed, but since you are asking: create a new workspace, import the sample project, execute these commands.

Since issue 152 was solved this works:

1. Run -> Run configurations... -> Spring Boot App -> New. 
2. Spring Boot tab -> Name the launch config "good launcher" and select class BootLauncherBugApplication as Main type
3. Click run: classpath is printed
4. Run -> Run configurations... -> Spring Boot App -> "good launcher"
5. Classpath tab -> advanced -> add folder -> boot-launcher-bug/empty-folder
4. Click run: classpath is as expected (same as in step 3 + folder from step 5)

But this is not yet working;
 
1. Run -> Run configurations... -> Spring Boot App -> New. 
2. Spring Boot tab -> call it "bad launcher" and select class BootLauncherBugApplication as Main type
3. Classpath tab -> advanced -> add folder -> boot-launcher-bug/empty-folder
4. Click run: classpath includes test folders ("/target/test-classes/") and dependencies (jmockit-1.31.jar)

Kind regards,
Stijn

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

I've fixed it and verified the fix from snapshot update site. Delivering this ticket.

**Comment by martinlippert** [comment]
Thanks for the additional details how to reproduce this, @bluebilt - much appreciated !!!

**Comment by bluebilt** [comment]
My pleasure, I can confirm that it is solved now. 
(Using nightly build 3.9.3.201801051941-CI-B1917)

Kind regards,
Stijn
