### ISSUE TITLE
Cant make a database connection to Oracle using the "service" format connection string

### ISSUE THREAD

**Issue by mcrobbj** [spring-projects/spring-ide#233]
Only supports the 
jdbc:oracle:thin:@myserver:port:SID
rather than the
jdbc:oracle:thin:@//myserver:port/database-service

The wizard seems to force the SID style string

I can connect thru spring with the SID style
https://stackoverflow.com/questions/4832056/java-jdbc-how-to-connect-to-oracle-using-service-name-instead-of-sid

**Comment by kdvolder** [comment]
> The wizard seems to force the SID style string

I'm sorry, but I have no idea which wizard you mean. Can you provide a bit more details? Maybe a sequence of steps to produce the problem.

**Comment by mcrobbj** [comment]
Open Perspective
Database Development
Database Connections - New
In Connection Profile select Oracle - Next
New Driver Definition
Oracle Thin Driver 11
Properties tab
Connection URL looking for the format jdbc:oracle:thin:@server:1521:db (SID based)

Enter the conenction url as jdbc:oracle:thin:@//server:1521/db
When you enter OK it takes you to a window that looks for the service name or SID and the host when you add thes the connection url is updated:
jdbc:oracle:thin:@//server:1521:ServiceName this is wrong it should be jdbc:oracle:thin:@//server:1521/ServiceName but there is NO way to change it.

**Comment by martinlippert** [comment]
This looks purely related to the Eclipse DataTools project, which implements the database perspective and all the related tools. Please file a bug for them here: https://bugs.eclipse.org/bugs/enter_bug.cgi?classification=DataTools

**Comment by mcrobbj** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=382063 is the bug, doesnt
look as if they have resolved it. May be worth including the link so others
can follow.

Thanks

John

**Comment by martinlippert** [comment]
Thanks for posting the link to the Eclipse bug, much appreciated.
