### ISSUE TITLE
Spring Tool Suite 3.9.1 - MacOS, Server restart keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by msivanesh** [spring-projects/spring-ide#236]
Issue: In Spring Tool Suite 3.9.1 on MacOS, if an user wants to restart the server using keyboard shortcut (Command + Option + R). he has to select the server with mouse and then using the keyboard shortcut. This defeats the purpose of keyboard shortcut. 

How it should be: The user should be able to restart the server without choosing the server using mouse pointer and by just typing the keyboard shortcut.

**Comment by martinlippert** [comment]
Can you explain in more detail which "Server" you are referring to? Tomcat? tc Server? Just a running Spring Boot app?

**Comment by msivanesh** [comment]
Tomcat v8.5. I tried with both Spring boot and Soring MVC web app.

**Comment by martinlippert** [comment]
In this case I would recommend to file a bug at Eclipse (https://bugs.eclipse.org/bugs/enter_bug.cgi?product=WTP%20ServerTools) for the WTP tools that provide the Servers view and the logic around that.
