### ISSUE TITLE
NullPointerException in BinaryModuleBinding while building workspace

### ISSUE THREAD

**Issue by mhldtna** [spring-projects/spring-ide#241]
I just upgraded an existing project to Java 9.0.1 and am getting this error while doing a build:

```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.BinaryModuleBinding.create(BinaryModuleBinding.java:64)
```

I found that this is a [known and fixed problem in Eclipse Oxygen](https://bugs.eclipse.org/bugs/show_bug.cgi?id=525522).  According to that page, the fix was "Verified for Eclipse Oxygen.2 (4.7.2) Build id: M20171115-1700" on November 16, 2017.

I upgraded my STS installation to springsource-tool-suite-3.9.2.RELEASE-e4.7.2-updatesite.zip from the [STS download page](https://spring.io/tools/sts/all), but the problem remains.  I guess STS has not yet picked up this bug fix from Eclipse itself.

Here are the details of my installation. (And, looking at this, I realize that I need to make STS itself run on Java 9.  But I don't think that will solve this problem.)

`
eclipse.buildId=3.9.1.201710111105-RELEASE-e47

java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.springsource.sts.ide -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide -data file:/C:/PDM16.4.1/ -product org.springsource.sts.ide
`

My question: when will this fix be available in STS?  Do I have any options?

Thanks.

**Comment by kdvolder** [comment]
You can try a snapshot build of STS from here:

http://dist.springsource.com/snapshot/STS/nightly-distributions.html

**Comment by kdvolder** [comment]
Let us know if works for you or not. We'd like to know :-)

**Comment by mhldtna** [comment]
Nope, it didn't help.  I installed the version from  http://dist.springsource.com/snapshot/TOOLS/nightly/e4.7, and my installation now says it is 

eclipse.buildId=3.9.1.201710111105-RELEASE-e47
java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide -product org.springsource.sts.ide -data file:/C:/PDM16.4.1/ -product org.springsource.sts.ide

... which is the same as above.

**Comment by mhldtna** [comment]
I just realized that I am realizing Eclipse/STS Neon, instead of Oxygen.  So I installed STS Oxygen and then the update from the first site that I referenced above.  And now that project compiles properly.  So I am closing this issue.

Thanks for your help.
