### ISSUE TITLE
I have some Errors in my error log in Spring tool suite(3.9.2). how can i fix it?

### ISSUE THREAD

**Issue by Shubham24006** [spring-projects/spring-ide#256]
I attached an error file here.

[error.txt](https://github.com/spring-projects/spring-ide/files/1832406/error.txt)

**Comment by kdvolder** [comment]
What is the actual problem? Is there something that doesn't work? We use the error log to try and diagnose specific problems. So please describe what you are actually trying to do and what doesn't work exactly.

Just quickly looking at the error log, it seems like maybe there may be some problems with STS connecting to the network. There are few errors in the log that could be indicative of network connection issues (have any firewalls / proxy).

Without a specific complaint about something that doesn't work there is really not much we can do here. Closing the ticket.
