### ISSUE TITLE
Javadoc popover when editing application.properties lacks context and can be confusing

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-ide#265]
When editing application.properties, a useful popover is shown that helps to complete a key. When part of the key is an enum, for example, `spring.jackson.serialization.*`, the popover displays the javadoc for the enum's value. This javadoc is displayed without context so it's not clear that it's Jackson's javadoc that's being displayed.

![screen shot 2018-04-05 at 12 31 56](https://user-images.githubusercontent.com/914682/38363725-b014efa6-38cd-11e8-844c-274bd02f3831.png)

By contrast, the same popover in IDEA makes it clear that it's Jackson's javadoc that is being shown:

![pasted image at 2018_04_05 01_29 pm](https://user-images.githubusercontent.com/914682/38363754-cafda696-38cd-11e8-8536-837b6b1349aa.png)

The context is important as it's useful to know where the javadoc is coming from. It's also important as it helps with things like `@since` information:

![screen shot 2018-04-05 at 12 36 19](https://user-images.githubusercontent.com/914682/38363817-0372ad32-38ce-11e8-89d6-74d238cfabfc.png)

I don't think it's clear that the 2.6 is a Jackson version.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

I doubt will be able to eliminate `@since` part... We could add a link to container java type for example. I've done that for sts4 LS.

**Comment by wilkinsona** [comment]
I wasn’t suggesting that the `@since` part should be eliminated. That was just an example of why the lack of context is confusing. If it were clear that the popover is showing Jackson’s javadoc, it would be clearer that the `@since` is a Jackson version.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

I suppose we'd need the following to give it more context:
```
Type link
Java element signature (?)
------------------------------------
Javadoc
------------------------------------
Classpath Entry container
```

Not sure if we could get those delimiters done nicely as they are shown in IntelliJ.

If content looks fine I can start looking into this.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I can see this being fixed in the old properties editor that we use in STS3 and partly in STS4, but I don't see the nice hover information in the language-server-based property editor when using that in Eclipse/STS4 distro. Can you double check?

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

STS4/Eclipse hovers probably don't look at nice at STS3... I'll double check... if it's the same as in VSCode then this is it for now for (M12)...

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

@mlippert This is how the hover looks for me. It's expected... for now... Maybe the signature will look JDTish soon (My PR for JDL LS just got merged, so we can grab the signature from JDT LS as well as javadoc content)
