### ISSUE TITLE
CF Plugin Does Not Authenticate

### ISSUE THREAD

**Issue by lshannon** [spring-projects/spring-ide#272]
Provides an Illegal State Exception when you try and submit a password to authenticate to Cloud Foundry
![cf-plugin-error](https://user-images.githubusercontent.com/3066950/38846871-a49cfea4-41cc-11e8-8a7f-96f71a24ab4e.png)

**Comment by martinlippert** [comment]
Worked again after restarting STS, so closing this issue for now. If this comes back, please comment/reopen and we will investigate in more detail.
