### ISSUE TITLE
Component Scan not working as expected

### ISSUE THREAD

**Issue by vinay4484** [spring-projects/spring-ide#281]
I have two different applications one for Business and one for Rest.  Both of them exist in one EAR. Rest is a war and business is a jar. I am using the business jar in Rest application.

In the business application i have annotated the Service Interface with @Component annotation.

**Business Module**  -- 
com.test.project.service  -- package name
BaseService.java  -- Interface which i am trying to autowire in my Rest Controller

**REST Module**
com.test.project.controller -- package name
BaseServiceController -- Controller Class where i am trying to auto wire BaseService.java  

**dispatcher-servlet.xml**

To register my business and controller classes available in  "com.test.project" package , i am mentioning the XML configuration as  <context:component-scan base-package="com.test.project" /> 
BUT  the container is not able to auto wire  BaseService.java in BaseServiceController.java, i am getting  BeanCreationException 

However if i am mentioning my base package name as "com.test.project.service" ,  BaseService.java is being auto wired into BaseServiceController.java, but if am trying to hit an endpoint in controller i am getting 404 as the controller is not registered in the container

**Comment by martinlippert** [comment]
As this is not directly an issue or question regarding the Spring IDE tooling (as far as I understood), I would recommend to ask this question on stackoverflow.
