### ISSUE TITLE
Multiple warnings after installing Spring IDE in Eclipse Photon RC1

### ISSUE THREAD

**Issue by jkopriva** [spring-projects/spring-ide#282]
Steps for reproduce: 
1. Install Eclipse Photon RC1 SDK
2. Install Spring IDE in Eclipse (3.9.3.201803200843-RELEASE)
3. Restart Eclipse and open Spring IDE

Warnings in errors log:
`null
org.eclipse.ui
Warning
Tue May 22 12:15:10 CEST 2018
org.eclipse.jdt.junit.ResultView: Deprecated relationship "fast" should be converted to "stack".
`
`null
org.eclipse.ui
Warning
Tue May 22 12:15:10 CEST 2018
org.springframework.ide.eclipse.aop.ui.navigator.aopReferenceModelNavigator: Deprecated relationship "fast" should be converted to "stack".
`
`null
org.eclipse.ui
Warning
Tue May 22 12:15:10 CEST 2018
org.eclipse.contribution.xref.ui.views.XReferenceView: Deprecated relationship "fast" should be converted to "stack".
`

**Comment by martinlippert** [comment]
I am not sure how do try to install the Spring IDE components, but the version that shows up for STS looks quite outdated and not compatible with Eclipse Photon anyway. Using the Eclipse Marketplace, you should get an up-to-date release version of the Spring Tools that are compatible with Photon. Can you try that?

**Comment by jkopriva** [comment]
@martinlippert Hi, I have updated description: I have used different version in my last test of this, please review it once again. Sorry for confusion.

**Comment by martinlippert** [comment]
Will take a look and tagged this for the next STS release.

Side note: changing an existing description is not always a great idea, since it renders answers and follow-up comments to that somewhat useless or irritating.

**Comment by martinlippert** [comment]
I tried to install the latest nightly snapshot builds of STS3 into Eclipse Photon SDK RC2 and that doesn't produce the errors mentioned above. How did you install the STS 3.9.3 release? Did you use a specific update site?

**Comment by jkopriva** [comment]
@martinlippert I havetretested it with Eclipse SDK, Version: Photon (4.8), Build id: I20180524-0900 and update site: http://download.jboss.org/jbosstools/updates/requirements/springide/3.9.3.201803200843-RELEASE/.
I still get the same warnings.

**Comment by nickboldt** [comment]
New versions of everything are available now to try to reproduce this problem.

Eclipse Photon RC4a:

https://ci.eclipse.org/packaging/job/photon.epp-tycho-build/345/artifact/org.eclipse.epp.packages/archive/

Spring IDE 3.9.4 R and 3.9.5 CI: 

http://dist.springsource.com/release/TOOLS/update/e4.8/
http://dist.springsource.com/snapshot/TOOLS/nightly/e4.8/

![image](https://user-images.githubusercontent.com/227597/41674501-30fce3b6-748e-11e8-99de-bbcc4c5c3f6b.png)

**Comment by jkopriva** [comment]
@nickboldt  I have tried both version: 3.9.4 and 3.9.5, but I still get the same warnings.

**Comment by martinlippert** [comment]
Since the mentioned features will move to maintenance mode shortly, we will not work on this anytime soon.
