### ISSUE TITLE
DB connection profiles not getting updated

### ISSUE THREAD

**Issue by sureshpec04** [spring-projects/spring-ide#283]
I am trying to configure DB connection profile in STS for mySQL. Initially, I gave the wrong user id/password to connect. Though the connection details are updated, **it still throws ping error**.  I tried deleting the connection profile but the old driver definitions are still showing up.  I tried this with latest release of STS 3.9.4.RELEASE it works though I provided valid details at the first attempt.

My Spring STS IDE version: 3.8.4.RELEASE 
Updated to 3.9.4.RELEASE
OS: Windows 10 amd64
JDK: JDK 8 u172

<img width="667" alt="spring sts database connnection profile error" src="https://user-images.githubusercontent.com/28023608/40379117-ef93a228-5dba-11e8-8105-b48c280a3c1d.png">

Is there any way to clear the driver definitions in my IDE? Appreciate your help!

Thanks,
Suresh

**Comment by martinlippert** [comment]
Since this is part of the Eclpse Data Tools, I am not really aware of the details how to clean the internal caches. I would recommend to ask this question on stackoverflow and tag it for the Eclipse Data Tools project.

**Comment by sureshpec04** [comment]
Thank you Martin. I posted this question in Stackoverflow: https://stackoverflow.com/questions/50489469/eclipse-data-tools-db-connection-profile-cache-not-cleared
