### ISSUE TITLE
Link to springframework.org in Spring IDE features is broken

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-ide#285]
I'm not sure of the correct terminology here. You can see the link by taking the following steps on macOS:

1. Click on `Eclipse -> About Eclipse` in the menu bar
2. Click the Spring IDE icon in the resulting window

I think have 4 features listed each of which shows the following when selected:

```
Spring IDE

Version: 3.9.4.201804120850-RELEASE

(c) Copyright 2005, 2016 Spring IDE Developers. All rights reserved.
Visit http://spring.io/tools

This product includes software developed by the Spring Framework Project
(http://www.springframework.org).
```

The Spring Framework link is broken as it tries to open `http://www.springframework.org).` (note the trailing `).`.

**Comment by martinlippert** [comment]
Thanks for catching this, I updated the link and removed the braces, should work again in the next CI build.
