### ISSUE TITLE
SocketTimeoutException while opening New Spring Starter Project wizard on STS running with Java 8

### ISSUE THREAD

**Issue by sandipsable111** [spring-projects/spring-ide#294]
SocketTimeoutException: connect timed out

 while opening New Spring Starter Project wizard on STS running with Java 8

**Comment by martinlippert** [comment]
Sounds like a network issue. Are you behind a firewall/proxy server?

**Comment by sandipsable111** [comment]
Thanks Martin,
Yes, It was network issue , After setting proxy its resolved .

**Comment by martinlippert** [comment]
OK, glad to hear that you solved the issue. Closing this item.

**Comment by shubhamm7** [comment]
can you help me how to resolve this issue.

**Comment by kdvolder** [comment]
@shubhamm7 We can try to help. But we don't know your network setup. So step 1, try to find out about that. As Martin asked..

>  Are you behind a firewall/proxy server?
