### ISSUE TITLE
Documentation: create master index.html about `New and Noteworthy`

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-ide#308]
Not sure if this issue should go here, but because is related with STS. It about `New and Noteworthy` I think has sense.

If I go to `https://docs.spring.io/sts/nan/` I can see a set of directories about the STS releases where for each one of them, for example for `395` is available the `v395` directory, if I go to `v395` I can see the `NewAndNoteworthy.html` file. If I do click there, I go to:

* `https://docs.spring.io/sts/nan/v395/NewAndNoteworthy.html`

I can play with the URL to go with previous versions, such as:

* `https://docs.spring.io/sts/nan/v394/NewAndNoteworthy.html`
* `https://docs.spring.io/sts/nan/v393/NewAndNoteworthy.html`

But there is no a complete order of the versions, for example part of the list is:

* `v380/                   2016-07-06 07:40    -   `
* `v381/                   2016-08-02 21:28    -   `
* `v382/                   2016-10-07 10:39    -   `
* `v383/                   2016-12-22 10:06    -   `
* `v384/                   2017-04-03 08:12    -   `
* `v390/                   2017-07-10 06:44    -   `
* `v391/                   2017-10-12 04:24    -   `
* `v392/                   2017-12-22 08:21    -   `
* `v393/                   2018-03-22 07:00    -   `
* `v394/                   2018-04-16 06:11    -   `
* `v395/                   2018-07-05 06:44    -   `

Thus for example, there are no from 385 to 389 

I suggest create in `https://docs.spring.io/sts/nan/` a master index listing all the `New and Noteworthy` for each release. Thus we avoid play around directly with the URL address

**Request One**: create master index.html about `New and Noteworthy`, where I can see the complete list of the STS releases and do click to anyone

Now, you would say, that currently for each one, for example for `https://docs.spring.io/sts/nan/v395/NewAndNoteworthy.html`, the latest until this day, in the bottom of the page exists the `New and Noteworthy for previous releases` section.

But I consider better add a master index. There we have the historical set of the releases

Now I did realise about the following, that in `https://spring.io/tools` exists in the top in the right part, the following:

```
Latest STS 
release notes.

Read more
```

If I do click it targets to `https://docs.spring.io/sts/nan/latest/NewAndNoteworthy.html` (observe the `latest` word in the URL) but shows 

* `Spring Tool Suite 3.9.0: New and Noteworthy`
 
and show must be

* `Spring Tool Suite 3.9.5: New and Noteworthy`

3.9.0 vs 3.9.5

**Request Two**: fix the URL to show the latest release or better if the master index suggested is created and now is used how a new reference. Thus the complete list is shared and disappears this situation where incorrectly a wrong version is shown the latest version.

**Comment by martinlippert** [comment]
I fixed the link to the latest version, so that points to the correct version again (the just released 3.9.6 version).

In addition to that each n&n doc contains references to previous n&n docs (for all the previous versions). You should not browse the directories yourself (and that should be technically prevented maybe anyway).

The missing versions that you mentioned do not exist, therefore there is no new and noteworthy.

Since we are approaching the release of the all-new Spring Tools 4 (with a re-designed webpage and a changelog that is hosted on the GitHub wiki), I tend to not change anything for the old STS 3 structure here.
