### ISSUE TITLE
Support for Spring Boot log groups

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-ide#325]
Spring Boot 2.1 introduced the concept of [log groups](https://docs.spring.io/spring-boot/docs/2.1.0.M4/reference/htmlsingle/#boot-features-custom-log-groups) with two out-of-the-box group: `web`, `sql`.

It would be nice if IJ had a way to auto-complete available groups on `logging.levels.` alongside the usual package browser. 

If an additional group is created in the project (via `logging.groups.xyz`), auto-completing `xyz` would be very nice as well.

Please note that this is represented by the `logger-name` hint whose description has been matched as of Spring Boot 2.1.

**Comment by martinlippert** [comment]
migrated this over to the STS4 issue tracker:
https://github.com/spring-projects/sts4/issues/102
