### ISSUE TITLE
Let STS transform from .yml to .properties

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-ide#331]
Hello STS team.

For:

```
Spring Tool Suite 4 

Version: 4.0.0.RELEASE
Build Id: 201809220817
```

It is able to convert from `.properties` to `.yml`

![screen shot 2018-12-01 at 5 06 57 pm](https://user-images.githubusercontent.com/2552795/49333527-76acd700-f58e-11e8-9653-40e9ca728bd9.png)

But once done this, how do the inverse?. 
it about convert from `.yml` to `.properties`. 
Currently is not possible 

![screen shot 2018-12-01 at 5 21 07 pm](https://user-images.githubusercontent.com/2552795/49333553-cd1a1580-f58e-11e8-986c-d8698e25152c.png)

Not sure if I am missing something.

**Comment by martinlippert** [comment]
We implementier the refactoring for .application -> .yml only, not the other way around, because our assumption is that people are more likely moving from property files to YAML files and not the other way around. Since that is "just" our assumption, we might be totally wrong about that... :-)

Do you see a real need to have the other way included in the tooling? Would you use that in real-world scenarios?

**Comment by manueljordan** [comment]
Hi Martin.

I know it is not critical, but perhaps the unique scenario that comes first to my mind is that in some demo about `Spring Boot` with `STS` without Git, the expositor is explaining about these two approaches, and thus well, he is not able to return to `.properties`. In someway seems a missing feature for STS itself.

Again, just was a simple request.

BTW: I have seen in twitter many developers that do not like Yaml. So once they had completed the experience with yaml, they are not able to return to properties. Of course, through Git it should be easy to return in time.

**Comment by Abdullah8006** [comment]
In our case we are using .yml propety file but we also at different times need all the keys from the .yml. It would be great if we can have something natively build in the IDE. There are however options online for that.

**Comment by martinlippert** [comment]
Development of these kind of features happens a part of the Spring Tools 4 project, so I will close this here and continue the discussion on https://github.com/spring-projects/sts4/issues/739.
