### ISSUE TITLE
problom for my ide 

### ISSUE THREAD

**Issue by aymenbraiek** [spring-projects/spring-ide#333]
when i create new starter projet 
i have this message 
SunCertPathBuilderException: unable to find valid certification path to requested target
![idea](https://user-images.githubusercontent.com/10660366/49497242-38eacf80-f868-11e8-989d-f48709dbbead.PNG)

**Comment by kdvolder** [comment]
Haven't seen that before in this wizard, but could it be that your machine has some extra security measures setup by corporate IT department. I think the error means that there's some problem verifying the ssl sertificate to connect to start.spring.io website over a https connection.

In other words, I think it is probably something about how your machine network environment is configured that is not allowing you through. A proxy, a firewall or some kind of custom certifcate authortiy management trying to tightly control what websites you can access.

Does this at all sound plausible w.r.t. to where your computer?

**Comment by aymenbraiek** [comment]
@kdvolder thanx problom reolved with you responce

**Comment by martinlippert** [comment]
Glad to hear that and thanks for letting us know.
