### ISSUE TITLE
Need Help with the following STS? bug

### ISSUE THREAD

**Issue by Netlokr** [spring-projects/spring-ide#335]
{data: {…}, status: 500, headers: ƒ, config: {…}, statusText: ""}
config: {method: "GET", transformRequest: Array(1), transformResponse: Array(1), paramSerializer: ƒ, jsonpCallbackParam: "callback", …}
data: {timestamp: 1545251830149, status: 500, error: "Internal Server Error", exception: "com.netflix.zuul.exception.ZuulException", message: "NUMBEROF_RETRIES_NEXTSERVER_EXCEEDED"}
headers: ƒ (d)
status: 500
statusText: ""

**Comment by kdvolder** [comment]
What is the problem exactly? I'm sorry but I have no idea.

Can you please describe in detail? I.e. give us something like description with a few 'steps to reproduce' that gives us something we can try to do. Then also explain what you are seeing happening and explain why this is a 'problem' by contrasting it with what you expected to happen if it was working correctly.

We'd really like to help you, but there just isn't enough information here for us to do anything helpful.

I'm closing this ticket now, but we can re-open it if you add more information.

**Comment by Netlokr** [comment]
We have a secure vault – www.netlok.com<http://www.netlok.com> (to get free registration) and the secure vault
www.netlokr.com<http://www.netlokr.com> . The system “works” – the problem is with scaling.

  *   The problem area pertains to getting an error – for accounts with large number of messages.

The code works (so why open a ticket):
       -      When we setup the code on testbed.ntlok.com – it works

  *   When we run it different AWS setup – a few accounts fail.

The failure message – is a timeout message. How do we change retry/timing setting(s)?

Felipe Carino
(805) 455-1499 (mobile)
