### ISSUE TITLE
Navigation inside xml file doesn't work

### ISSUE THREAD

**Issue by fkomar** [spring-projects/spring-ide#345]
If I'm inside big spring xml file and I use F3 to jump to bean declaration. After that I use Alt + left arrow and expect to get back to previous position inside that same xml file. Instead I get back to previous position in java file.

**Comment by BoykoAlex** [comment]
The problem is that XML editor is a multipage editor and Eclipse's navigation history doesn't seem to record proper editor ID in this case. Need to raise eclipse bugzilla for this I think

**Comment by martinlippert** [comment]
So closing this here and removing the release milestone marker again.
@fkomar please open a bug for this at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform
