### ISSUE TITLE
The EGit Nightly Repository is shipped with STS 4.2.0

### ISSUE THREAD

**Issue by eugenp** [spring-projects/spring-ide#375]
Hi, 
Opening up a quick issue I noticed here - and that's the fact that the Nightly repo of EGit is shipped along with STS 4.2.0. 
Here's what the repo looks like: 
_EGit P2 Repository = http://download.eclipse.org/egit/updates-nightly/_

I think the stable repo should be the one that's active: 
_http://download.eclipse.org/egit/updates_

Hope that helps. 
Cheers, 
Eugen.

**Comment by martinlippert** [comment]
Hey Eugen, not sure what you exactly mean. The egit components that are included in the STS 4.2.0 distribution are of version `5.3.0.201903130848-r`, which is the released version from Eclipse 2019-03. Where did you find the nightly egit components?

**Comment by eugenp** [comment]
Hey @martinlippert  - sorry for the radio silence here, I missed your reply. 
So, what happened was that a simple "Check for updates" in that version of STS was resulting in an error, with a message related to not being able to connect to that updates-nightly repo. 
Now, given I didn't make any change to STS, I assume that was bundled with the distribution. 
But, well, that's no longer the case (just checked with the latest version of STS) so one way or another, it got fixed. 
Closing this one. 
Thanks, 
Eugen.

**Comment by martinlippert** [comment]
@eugenp No problem and thanks for coming back to this with these good news and letting us know. Much appreciated.
