### ISSUE TITLE
Tag coloring fails if tag has square brackets. (3.9.8.201903260659-RELEASE)

### ISSUE THREAD

**Issue by jmax01** [spring-projects/spring-ide#377]
Tag coloring fails if tag has square brackets.

The line below will not be colored: 
```yaml
logging.level.org.springframework.kafka.listener.[KafkaMessageListenerContainerListenerConsumer]: INFO
```

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

This doesn't seem to be a problem that is reproducible in STS 4 (but yes, it *is* reproducible in STS3). So I think this is just an issue with the old Yedit-based 'legacy' editor in STS 3. 

We will not fix this bug because:

- this is hard for us to fix (bug is not in our own code)
- the legacy editor will be phased out anyways
- The problem is mostly cosmetic so not worth the amount of effort it would take to fix.

**Comment by jmax01** [comment]
Welp my attempt to upgrade to sts 4 to address this issue corrupted my installation and I had to reinstall and reconfigure.

The Eclipse rollback feature was no help and simply made things worse, to the point it could not even start Eclipse.

**Comment by martinlippert** [comment]
@jmax01 Urgh..... Super sorry to hear that, what a bad experience. I always recommend to start with a fresh STS4 installation when switching over from STS3 in any case. Hope that you could at least save the workspace from being corrupted or damaged.

If you want to share more details about how to tried to upgrade to STS4, they would be more than welcome. I could take a look to see what went wrong and think about possible ways to prevent those things from happening again in the future.

**Comment by jmax01** [comment]
Yes I have the workspace and the install directory saved.  

The first indication of corruption was that the update site list was empty in _Preferences->Install/Update->Available Software Sites was Empty._

If you can name anything specific that would help I might be able to provide it.

**Comment by martinlippert** [comment]
@jmax01 I've come across the deleted update site preferences myself a while ago, but was never able to figure out what caused this. Strange bug indeed.

Can you still open the old broken installation or does it not even startup anymore?

**Comment by martinlippert** [comment]
If it starts up, a look into the Error Log view could reveal some interesting information.
