### ISSUE TITLE
Issue with Spring Tool Suite 4.0 - Auto Complete not working on application.properties

### ISSUE THREAD

**Issue by aru-royal** [spring-projects/spring-ide#388]
Hi Team,
     I download spring tool suite 4 from spring site.  While entering keys on application.properties I am not getting auto complete suggestion , I tried on spring. and logging. , eventhough I see leaf symbol to application.properties , I am still not able get any suggestions.

**Comment by aru-royal** [comment]
Closing issue , as I am able to see auto complete suggestion now

**Comment by martinlippert** [comment]
@aru-royal good to hear that you got it working now. Any idea what caused the trouble in the first place or how you made it work on your end? Might be interesting for other users having when running into the same or a similar issue. Thanks!!!

**Comment by aru-royal** [comment]
I didn't do any additional config changes , It just worked.  Thanks for following up on this issue.

**Comment by kdvolder** [comment]
Sometimes it takes time before the language server process recieves classpath information from the IDE side (e.g. because the IDE is still downloading dependency jars from maven). Until the language server has classpath of the project completions and other functionality that reads data from the classpath will not work. This may be what was happening.

**Comment by aru-royal** [comment]
Thanks for clarification.
    On Friday, August 2, 2019, 05:02:17 PM GMT+1, Kris De Volder <notifications@github.com> wrote:  
 
 
Sometimes it takes time before the language server process recieves classpath information from the IDE side (e.g. because the IDE is still downloading dependency jars from maven). Until the language server has classpath of the project completions and other functionality that reads data from the classpath will not work. This may be what was happening.
