### ISSUE TITLE
sts3 where download？

### ISSUE THREAD

**Issue by startjava** [spring-projects/spring-ide#409]
https://spring.io/tools3/sts/all

can not find download <a>

**Comment by martinlippert** [comment]
@startjava Yes, indeed, that page got lost in the redesign of the spring.io pages. We are sorry for that mistake and are working on bringing an STS3 downloads page back.

In the meantime, please take a look here for the downloads:
https://github.com/spring-projects/spring-ide/wiki/Downloads-for-the-Spring-Tool-Suite-3

But please keep in mind that the Spring Tool Suite 3 is on minimal maintenance and that it is recommended to switch to the latest Spring Tools 4 from here: https://spring.io/tools.

If you have specific reasons why you don't want to migrate to the Spring Tools 4, please let us know what you are missing or what doesn't work that you urgently need. That kind of feedback would be very very welcome and appreciated.

**Comment by martinlippert** [comment]
I moved the page over here: https://github.com/spring-projects/toolsuite-distribution/wiki/Spring-Tool-Suite-3

**Comment by wbashir** [comment]
@martinlippert i had to downgrade to STS 3.5 due to no Spring Roo support for feedback.

**Comment by martinlippert** [comment]
@wbashir Thanks for the feedback. Indeed, the Roo support is not available for Spring Tools 4.
