### ISSUE TITLE
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.

### ISSUE THREAD

**Issue by kosarajusandeep** [spring-projects/spring-ide#416]
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=C__Users_sk1025_eclipse_java-2020-03_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Users\sk1025\.p2\pool\plugins\com.sap.adt.tools.sqlm_3.8.4.jar

**Comment by martinlippert** [comment]
Looks like something went wrong with that JAR file (which does not come as part of the Spring Tools installation or distribution). I would recommend to delete that JAR file and try the install process again. If that doesn't help, I would ask the provider of that third-party add-on for help.
