### ISSUE TITLE
Marketplace update site urls of Spring Tools 3 Add-On points to nightly build

### ISSUE THREAD

**Issue by jpraet** [spring-projects/spring-ide#420]
Hi, the update sites on https://marketplace.eclipse.org/content/spring-tools-3-add-spring-tools-4 point to a nightly build snapshot version.

![image](https://user-images.githubusercontent.com/2212615/98104411-b412f100-1e96-11eb-80e7-3006588814ca.png)

I suppose that's by mistake?

**Comment by martinlippert** [comment]
@jpraet Thanks for pointing us at this, but this is actually correct (at least at the moment). The latest release build of STS3 components is not compatible with the latest STS4 release, therefore we need a specific SNAPSHOT build of the STS3 components that are updated to be compatible with the latest STS4 releases.

We will provide an updated release build of STS3 components around the next Eclipse release (late December), but that will probably be the last STS3 release going forward.

**Comment by martinlippert** [comment]
If you still use the STS3 components, please let us know what prevents you from working with STS4 exclusively, so that we can prioritize work on STS4 to make the migration smoother and to fill missing parts.

**Comment by jpraet** [comment]
@martinlippert Thanks, I'm trying without the STS3 add-on now because I have to admit I just installed it out of habit. But we do have lots of legacy spring projects with XML application context configurations.

I've initially noticed these missing parts:
* no autocomplete for `<constructor-arg name="...">`
* no validation error for invalid `<bean class="...">`
* no validation error for invalid `<property name="...">`

**Comment by kdvolder** [comment]
There's an option for enabling some xml support in STS 4. It probably does not do all that you want, and you may run into some bugs, but if you haven't turned it on, please do. Then we'd like to hear what is *still* missing or isn't working the way that you want/need.

To enable it go to Preferences >> Language Servers >> Spring Language Servers >> Spring Boot Language Server >> Spring XML Config".

**Comment by kdvolder** [comment]
> no validation error for invalid <bean class="...">

... Yes, I think validation is 'weak'. I think it only does basic Schema validation, but nothing 'Spring Specific'. 

Examples of exactly what kind of things you expect would be good. We would like to avoid just going back and porting all of the STS 3 over to STS 4. So if you can provide details like 'I have this kind of xml, and I expec that kind of a error because...' that would be very helpful. We can then think on how to make those kinds of things be checked for specifically and reported as warnings / errors.

**Comment by martinlippert** [comment]
@jpraet I created enhancement request items for all three suggestions in the STS4 repo. Please feel free to follow those to be updated about progress and further discussions / questions.

**Comment by martinlippert** [comment]
@jpraet And please keep those items coming that you are missing from the STS4 tooling when dealing with those older projects. We will definitely not port all of the old STS3 features around XML editing over, but it is good to know which features users with those legacy projects would benefit from the most to prioritize the work accordingly. So please keep the feedback coming, much appreciated.

**Comment by martinlippert** [comment]
@jpraet https://github.com/spring-projects/sts4/issues/562 is fixed now.
