### ISSUE TITLE
JPA Java Change Event Handler (Waiting)

### ISSUE THREAD

**Issue by pavan-chakka** [spring-projects/spring-ide#430]
Hello,

Am using STS 3.9.8 in Mac, and am seeing 'JPA Java Change Event Handler' very frequently, and I am not able to edit any code for almost 2 hours until it is completed, and din't find any good solution in google to avoid this. I have disabled all validations including JPA validation, but that also didn't helped. Does any experienced this, and have any solution for this, please enlighten. 

Thank you!

**Comment by martinlippert** [comment]
This seems to be related to the JPA tooling in Eclipse. Here are a few thoughts/suggestions:

- looks like you are using an old STS version, please update to the latest Spring Tools 4 for Eclipse 4.12.0.RELEASE
- you could uninstall the JPA tooling from your Eclipse install to see if that helps

Is there any specific reason that you are still using this old version?

**Comment by pavan-chakka** [comment]
Hi Martin, few months back, I installed STS4 and then it did not allowed me to run my project and gave various errors, so haven't spent time resolving them. Today I installed 4.12.0 and luckily, I was able to run my project. Will continue working in 4.12.0 and will monitor if I encounter JPA Java Change Event Handler in STS 4. Thank you.

**Comment by martinlippert** [comment]
In case something comes up, please report it here: https://github.com/spring-projects/sts4/issues
