### ISSUE TITLE
Gradle and Boot Dashboard

### ISSUE THREAD

**Issue by Blacktiger** [spring-projects/spring-ide#59]
I have a spring boot project with Actuator installed and I wanted to setup the info endpoint to have some properties from a gradle file. So I configured gradle to processResources by adding this to my build.gradle.

```
processResources {
	expand(project.properties)
}
```

Then I changed my bootstrap.yml to use placeholders for the appropriate gradle.properties like so.

```
info:
  build:
    name: ${name}
```

Now I'm unable to run the application via the Boot Dashboard. It looks to me like the processResources isn't being run against whatever Boot Dashboard selects to generate the artifact to run. The exception I get when the application is run would indicate that Spring is trying to handle the replacement instead of Gradle already having done the replacement.

```
Could not resolve placeholder 'name' in string value "${name}"
```

I'm not sure if this is the right place to report this issue, maybe it's a bug in the Gradle STS and Buildship plugins? I've tried both and neither of them make a difference.

**Comment by martinlippert** [comment]
How do you run the project from STS or Eclipse (when not starting it from the boot dashboard)?

**Comment by Blacktiger** [comment]
I've tried running via the Spring Boot Dashboard, and as a Java application. I did some additional research and it sounds to me like this is a problem with the Gradle plugins not the STS dashboard itself.
