### ISSUE TITLE
Not able to download Eclipse dependency

### ISSUE THREAD

**Issue by mukteshkrmishra** [spring-projects/spring-ide#62]
Hi,

I am getting following error while trying to build project: It looks like it is not able to download dependencies from eclipse repo.
Can anybody please let me know the exact setting for eclipse repo.

No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.eclipse.jdt.core 3.7.0.v_OTDT_r200_201106070730 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.7.1.v_OTDT_r201_201109101025 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.jdt.core 3.7.3.v_OTDT_r202_201202051448 to org.eclipse.objectteams.otdt.core.patch.feature.group [2.0.0,3.0.0).; Unable to satisfy dependency from org.eclipse.swtbot.eclipse.finder 2.4.0.201604200752 to bundle org.eclipse.e4.ui.model.workbench 0.0.0.; Unable to satisfy dependency from org.eclipse.swtbot.eclipse.finder 2.4.0.201604200752 to bundle org.eclipse.e4.ui.workbench.renderers.swt 0.0.0.; Unable to satisfy dependency from org.springframework.ide.eclipse.boot 3.8.2.qualifier to bundle com.fasterxml.jackson.core.jackson-core 0.0.0.; Unable to satisfy dependency from org.springframework.ide.eclipse.boot 3.8.2.qualifier to bundle com.fasterxml.jackson.core.jackson-databind 0.0.0.; Unable to satisfy dependency from org.springframework.ide.eclipse.boot 3.8.2.qualifier to bundle com.fasterxml.jackson.core.jackson-annotations 0.0.0.; Unable to satisfy dependency from org.springframework.ide.eclipse.boot.wizard 3.8.2.qualifier to bundle org.apache.commons.compress 0.0.0.; Unable to satisfy dependency from org.springsource.ide.eclipse.commons.livexp 3.8.1.201607071354-CI-B220 to bundle com.google.guava 15.0.0.; No solution found because the problem is unsatisfiable.]

**Comment by martinlippert** [comment]
What exactly are you trying to do? And what exactly did you execute on the command line? If running a maven tycho build for this, you usually need to activate the profile for the Eclipse version that you are targeting, so maybe that is missing?

**Comment by mukteshkrmishra** [comment]
Hi,

As mentioned in the readme, I was trying to build it using profile e37 when I got this error.

All my dependencies were downloaded except Eclipse specific dependencies.

Thanks,
Muktesh

**Comment by martinlippert** [comment]
Hmmm... Could be that the readme is slightly out of date... Can you try to run this with -Pe45?

**Comment by mukteshkrmishra** [comment]
Got it!! Switching for Eclipse Mars (4.5) helped. Please update the read me as looks like dependencies for Eclipse Indigo (3.7) no longer exists in Eclipse Repo.

**Comment by martinlippert** [comment]
Glad to hear that is working for you. I updated the readme and therefore closing this now. Thanks for the feedback!!!
