### ISSUE TITLE
Error mentioned in Spring editor but no indication on what it is and nothing in Problems view

### ISSUE THREAD

**Issue by apupier** [spring-projects/spring-ide#83]
I am in the state where I have an error mentioned at the top of the Beans Editor, but I have no indication on what is the error. The problems view have no error neither and the Source tab neither.
![image](https://cloud.githubusercontent.com/assets/1105127/20799146/9b95acb4-b7e1-11e6-8af3-46092055a5f2.png)

![image](https://cloud.githubusercontent.com/assets/1105127/20799154/9fd040f0-b7e1-11e6-8679-9b3cad5aef56.png)

and here is the content of my java Bean:
`package com.example;

public class MyBean {
	
	private String name;
	private String age;

	public MyBean(String name, String age) {
		// TODO Auto-generated constructor stub
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

}
`

**Comment by martinlippert** [comment]
Do you see any errors in the Error Log View? Maybe something went wrong in the background. Can you take a look if there is something related showing up?

**Comment by apupier** [comment]
I don't have anymore the log.
I don't reproduce the issue, when I open the editor I have no error now.
I close this issue then... i will reopen if i reproduce it.

**Comment by martinlippert** [comment]
Ok, sounds good. Thanks!
