### ISSUE TITLE
Initializr wizard bombs out with "no internet" message when it gets a 500

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-ide#86]
This is the error in the logs:

```
IOException: Server returned HTTP response code: 500 for URL: http://start.spring.io/dependencies?bootVersion=2.0.0.BUILD-SNAPSHOT
```

There clearly is an internet connection and we can reach the service, but it returned a 500, so telling the user that there is no internet connection is a bit misleading and confusing.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

The new wizard doesn't have that problem anymore I think.
