### ISSUE TITLE
Dashboard never finishes starting application

### ISSUE THREAD

**Issue by dlaidlaw** [spring-projects/spring-ide#88]
Spring Tool Suite
 - Version: 3.8.2.RELEASE  
 - Build Id: 201610040743  
 - Platform: Eclipse Neon.1 (4.6.1)  

Spring Boot in Project
 -1.4.2.RELEASE  

Project used: https://github.com/dlaidlaw/spring-boot-sample.git

The above project is a very simple webapp. Just a hello world.

When starting any spring-boot application using the Dashboard view, the spinning arrows next to the application never stop spinning, the port number never gets displayed. There is also difficulty in stopping the application. Sometimes pressing the stop icon in the dashboard stops it right away, other times it starts a background job to stop it that never seems to finish. This also affects restarts, of course.

The launch config is the one created by the dashboard, nothing changed in it.

The application itself actually does start and run normally with no issues. What would stop the dashboard from detecting the application has started?

**Comment by kdvolder** [comment]
> What would stop the dashboard from detecting the application has started?

STS uses a JMX bean to which it connects via a socket to 
 - ask whether app is 'started'
 - ask the app to 'shutdown nicely' (when you click stop button).

So it would seem that STS cannot connect to the JMX bean for some reason.

It could be some firewall or network setting (.e.g: What would stop the dashboard from detecting the application has started?)

Or it could be that your app has a more custom configuration than the typical boot app and the JMX bean has not been enabled. I have seen one example of this where a user 'trimmed down' their config and by doing so had removed the JMX admin bean from their app. I was looking for the issue ticket but couldn't find it unfurtunately. 

> The launch config is the one created by the dashboard, nothing changed in it.

What about the app itself? How was that created? If you create one with 'New >> Spring Starter Project' wizard then it should work (barring any funky network / firewall settings that may prohibit local socket connections between STS and the boot app to be established)

**Comment by dlaidlaw** [comment]
After much experimentation, it was not any issues with any of my projects, but rather an errant DNS entry in /etc/hosts. I am not sure how my /etc/hosts file got updated, but the DNS entry in it for my own machine had the wrong IP address. Removing that entry fixed the problem.

Thanks for the tips!

**Comment by martinlippert** [comment]
Glad to hear that you found the root cause of this.
