### ISSUE TITLE
BuildShip support not working with BuildShip 2.0

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-ide#90]
See: http://stackoverflow.com/questions/41639980/spring-sts-does-not-work-with-gradle
See: https://www.pivotaltracker.com/story/show/137732847

We have a version constraint limiting us to BS < 2.0.

Relaxing the version constraint also reveals that our code no longer compiles against BS 2.0 because of API changes.

**Comment by kdvolder** [comment]
A fix has been pushed to master. The fix contributes an extra import strategy for BuildShip version 2.x. The old stratgey has some minor changes to label it more appropriately as well. So now, the wizard's pull-down menu provides separate choices for Buildship 1.x and Buildship 2.x.

The fix is available from snapshot update site: 
https://dist.springframework.org/snapshot/IDE/nightly

**Comment by khat33b** [comment]
I am getting a `The specified key does not exist.` error when clicking on the link. How long till this bug fix be updated to STS?

**Comment by martinlippert** [comment]
The URL mentioned above is not meant to be used via a browser, since it doesn't serve an index page or anything like that. Therefore the message is expected and correct.

You should instead use the URL above in Eclipse/STS in the "Install New Software" dialog and install the updated features there.

If you want to use a ready-to-use STS distribution that includes this bug fix, you can go to our nightly download page at: http://dist.springsource.com/snapshot/STS/nightly-distributions.html. I would recommend to use the distro on Eclipse 4.6.2 for general use.

**Comment by titoc** [comment]
@martinlippert 
"Install New Software" gives 
- No repository found at https://dist.springframework.org/snapshot/IDE/nightly.

**Comment by martinlippert** [comment]
Yes, this is a temporary outage of our nightly CI builds. We hope to get those update sites back online soon. Will update you here as soon as the site is back again.

**Comment by martinlippert** [comment]
We are sorry for the inconvenience.

**Comment by gridface** [comment]
Is there still an outage?  Is there an alternate link my development team can use?

**Comment by walidstark** [comment]
@martinlippert When can I access the website? I'm currently working on a project. I hope this issue will be solved soon.

**Comment by martinlippert** [comment]
I hope to have the CI builds back sometime today, working on them at the moment.

**Comment by martinlippert** [comment]
The nightly Spring IDE repository is back online. Sorry again for the inconvenience!!!

**Comment by kishm** [comment]
Is this fix included in Spring Tool Suite 3.9.0 which is released on July 10, 2017.  I am getting same issue on Spring Tool Suite 3.9.0 with Gradle BuildShip 2.0 (2.1.0)?

**Comment by dejan2609** [comment]
Just to correct my self: linked issue is not a regression, but duplicate.
