### ISSUE TITLE
Long pause  every time I save a source file

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-ide#94]
It's getting a bit ridiculous here. Every time I hit "Save" I get a 1-2min pause while the workspace rebuilds.

**Comment by dsyer** [comment]
[threads.txt](https://github.com/spring-projects/spring-ide/files/792843/threads.txt)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

It looks like the build is re-creating the beans model behind the scenes and is doing that work while you observe the 1-2min pause.

I wonder why it takes so long to create that model and would love to find out that takes so long. Can you run YourKit, attach a profiler to the IDE process, and record a CPU profiling (optimal would be in "Tracing" mode). Would be really interesting to see that data.

In addition to that you could avoid this by removing the Spring nature from the project. Then the model isn't created anymore and your build should be back to normal.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

Did you have the chance to capture a performance profiling for me?

**Comment by dsyer** [comment]
I haven't, sorry, and of course it's not behaving the same way now. I can still get the data if you want?

**Comment by martinlippert** [comment]
Ok, I will close this for now. If you come across the same situation, please comment and we will re-open this issue. Thanks a lot for your help!!!
